settings:
  token:
  parse_mode: html

buttons:
  swap:
    unique: swap
    callback_data: '{{ . }}'
    text: 🔄 {{ . }}
  select:
    unique: select
    callback_data: '{{ .Ticker }}'
    text: ✅ {{ .Text }}
  done:
    unique: done
    text: Завершить

markups:
  swap:
    - [ swap ]

  select:
    - [ select, select, select, select, select ]
    - [ select ]
    - [ done ]

config:
  currencies:
    - RUB
    - USD
    - EUR
    - GBP
  mariadb.host:
  mariadb.port:
  mariadb.login:
  mariadb.password: