settings:
  token:
  parse_mode: html

buttons:
  swap:
    unique: swap
    callback_data: '{{ . }}'
    text: 🔄 {{ . }}

markups:
  swap:
    - [ swap ]

config:
  currencies:
    - RUB
    - USD
    - EUR
    - GBP
  mariadb.host:
  mariadb.port:
  mariadb.login:
  mariadb.password: