// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/arsquote"
	"main/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ARSQuoteDelete is the builder for deleting a ARSQuote entity.
type ARSQuoteDelete struct {
	config
	hooks    []Hook
	mutation *ARSQuoteMutation
}

// Where appends a list predicates to the ARSQuoteDelete builder.
func (aqd *ARSQuoteDelete) Where(ps ...predicate.ARSQuote) *ARSQuoteDelete {
	aqd.mutation.Where(ps...)
	return aqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aqd *ARSQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aqd.hooks) == 0 {
		affected, err = aqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ARSQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aqd.mutation = mutation
			affected, err = aqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aqd.hooks) - 1; i >= 0; i-- {
			if aqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aqd *ARSQuoteDelete) ExecX(ctx context.Context) int {
	n, err := aqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aqd *ARSQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: arsquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: arsquote.FieldID,
			},
		},
	}
	if ps := aqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aqd.driver, _spec)
}

// ARSQuoteDeleteOne is the builder for deleting a single ARSQuote entity.
type ARSQuoteDeleteOne struct {
	aqd *ARSQuoteDelete
}

// Exec executes the deletion query.
func (aqdo *ARSQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := aqdo.aqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{arsquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aqdo *ARSQuoteDeleteOne) ExecX(ctx context.Context) {
	aqdo.aqd.ExecX(ctx)
}
