// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/bhdquote"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BHDQuoteCreate is the builder for creating a BHDQuote entity.
type BHDQuoteCreate struct {
	config
	mutation *BHDQuoteMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (bqc *BHDQuoteCreate) SetPrice(f float64) *BHDQuoteCreate {
	bqc.mutation.SetPrice(f)
	return bqc
}

// SetTimestamp sets the "Timestamp" field.
func (bqc *BHDQuoteCreate) SetTimestamp(t time.Time) *BHDQuoteCreate {
	bqc.mutation.SetTimestamp(t)
	return bqc
}

// SetID sets the "id" field.
func (bqc *BHDQuoteCreate) SetID(i int) *BHDQuoteCreate {
	bqc.mutation.SetID(i)
	return bqc
}

// Mutation returns the BHDQuoteMutation object of the builder.
func (bqc *BHDQuoteCreate) Mutation() *BHDQuoteMutation {
	return bqc.mutation
}

// Save creates the BHDQuote in the database.
func (bqc *BHDQuoteCreate) Save(ctx context.Context) (*BHDQuote, error) {
	var (
		err  error
		node *BHDQuote
	)
	if len(bqc.hooks) == 0 {
		if err = bqc.check(); err != nil {
			return nil, err
		}
		node, err = bqc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BHDQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = bqc.check(); err != nil {
				return nil, err
			}
			bqc.mutation = mutation
			if node, err = bqc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(bqc.hooks) - 1; i >= 0; i-- {
			if bqc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bqc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bqc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bqc *BHDQuoteCreate) SaveX(ctx context.Context) *BHDQuote {
	v, err := bqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bqc *BHDQuoteCreate) Exec(ctx context.Context) error {
	_, err := bqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bqc *BHDQuoteCreate) ExecX(ctx context.Context) {
	if err := bqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bqc *BHDQuoteCreate) check() error {
	if _, ok := bqc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "BHDQuote.price"`)}
	}
	if _, ok := bqc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "Timestamp", err: errors.New(`ent: missing required field "BHDQuote.Timestamp"`)}
	}
	return nil
}

func (bqc *BHDQuoteCreate) sqlSave(ctx context.Context) (*BHDQuote, error) {
	_node, _spec := bqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (bqc *BHDQuoteCreate) createSpec() (*BHDQuote, *sqlgraph.CreateSpec) {
	var (
		_node = &BHDQuote{config: bqc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bhdquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bhdquote.FieldID,
			},
		}
	)
	if id, ok := bqc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bqc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: bhdquote.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := bqc.mutation.Timestamp(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bhdquote.FieldTimestamp,
		})
		_node.Timestamp = value
	}
	return _node, _spec
}

// BHDQuoteCreateBulk is the builder for creating many BHDQuote entities in bulk.
type BHDQuoteCreateBulk struct {
	config
	builders []*BHDQuoteCreate
}

// Save creates the BHDQuote entities in the database.
func (bqcb *BHDQuoteCreateBulk) Save(ctx context.Context) ([]*BHDQuote, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bqcb.builders))
	nodes := make([]*BHDQuote, len(bqcb.builders))
	mutators := make([]Mutator, len(bqcb.builders))
	for i := range bqcb.builders {
		func(i int, root context.Context) {
			builder := bqcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BHDQuoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bqcb *BHDQuoteCreateBulk) SaveX(ctx context.Context) []*BHDQuote {
	v, err := bqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bqcb *BHDQuoteCreateBulk) Exec(ctx context.Context) error {
	_, err := bqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bqcb *BHDQuoteCreateBulk) ExecX(ctx context.Context) {
	if err := bqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
