// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/brlquote"
	"main/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BRLQuoteQuery is the builder for querying BRLQuote entities.
type BRLQuoteQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.BRLQuote
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BRLQuoteQuery builder.
func (bqq *BRLQuoteQuery) Where(ps ...predicate.BRLQuote) *BRLQuoteQuery {
	bqq.predicates = append(bqq.predicates, ps...)
	return bqq
}

// Limit adds a limit step to the query.
func (bqq *BRLQuoteQuery) Limit(limit int) *BRLQuoteQuery {
	bqq.limit = &limit
	return bqq
}

// Offset adds an offset step to the query.
func (bqq *BRLQuoteQuery) Offset(offset int) *BRLQuoteQuery {
	bqq.offset = &offset
	return bqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bqq *BRLQuoteQuery) Unique(unique bool) *BRLQuoteQuery {
	bqq.unique = &unique
	return bqq
}

// Order adds an order step to the query.
func (bqq *BRLQuoteQuery) Order(o ...OrderFunc) *BRLQuoteQuery {
	bqq.order = append(bqq.order, o...)
	return bqq
}

// First returns the first BRLQuote entity from the query.
// Returns a *NotFoundError when no BRLQuote was found.
func (bqq *BRLQuoteQuery) First(ctx context.Context) (*BRLQuote, error) {
	nodes, err := bqq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{brlquote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bqq *BRLQuoteQuery) FirstX(ctx context.Context) *BRLQuote {
	node, err := bqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BRLQuote ID from the query.
// Returns a *NotFoundError when no BRLQuote ID was found.
func (bqq *BRLQuoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bqq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{brlquote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bqq *BRLQuoteQuery) FirstIDX(ctx context.Context) int {
	id, err := bqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BRLQuote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BRLQuote entity is found.
// Returns a *NotFoundError when no BRLQuote entities are found.
func (bqq *BRLQuoteQuery) Only(ctx context.Context) (*BRLQuote, error) {
	nodes, err := bqq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{brlquote.Label}
	default:
		return nil, &NotSingularError{brlquote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bqq *BRLQuoteQuery) OnlyX(ctx context.Context) *BRLQuote {
	node, err := bqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BRLQuote ID in the query.
// Returns a *NotSingularError when more than one BRLQuote ID is found.
// Returns a *NotFoundError when no entities are found.
func (bqq *BRLQuoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bqq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = &NotSingularError{brlquote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bqq *BRLQuoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := bqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BRLQuotes.
func (bqq *BRLQuoteQuery) All(ctx context.Context) ([]*BRLQuote, error) {
	if err := bqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return bqq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (bqq *BRLQuoteQuery) AllX(ctx context.Context) []*BRLQuote {
	nodes, err := bqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BRLQuote IDs.
func (bqq *BRLQuoteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := bqq.Select(brlquote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bqq *BRLQuoteQuery) IDsX(ctx context.Context) []int {
	ids, err := bqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bqq *BRLQuoteQuery) Count(ctx context.Context) (int, error) {
	if err := bqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return bqq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (bqq *BRLQuoteQuery) CountX(ctx context.Context) int {
	count, err := bqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bqq *BRLQuoteQuery) Exist(ctx context.Context) (bool, error) {
	if err := bqq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return bqq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (bqq *BRLQuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := bqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BRLQuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bqq *BRLQuoteQuery) Clone() *BRLQuoteQuery {
	if bqq == nil {
		return nil
	}
	return &BRLQuoteQuery{
		config:     bqq.config,
		limit:      bqq.limit,
		offset:     bqq.offset,
		order:      append([]OrderFunc{}, bqq.order...),
		predicates: append([]predicate.BRLQuote{}, bqq.predicates...),
		// clone intermediate query.
		sql:    bqq.sql.Clone(),
		path:   bqq.path,
		unique: bqq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BRLQuote.Query().
//		GroupBy(brlquote.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (bqq *BRLQuoteQuery) GroupBy(field string, fields ...string) *BRLQuoteGroupBy {
	group := &BRLQuoteGroupBy{config: bqq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := bqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return bqq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.BRLQuote.Query().
//		Select(brlquote.FieldPrice).
//		Scan(ctx, &v)
//
func (bqq *BRLQuoteQuery) Select(fields ...string) *BRLQuoteSelect {
	bqq.fields = append(bqq.fields, fields...)
	return &BRLQuoteSelect{BRLQuoteQuery: bqq}
}

func (bqq *BRLQuoteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range bqq.fields {
		if !brlquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bqq.path != nil {
		prev, err := bqq.path(ctx)
		if err != nil {
			return err
		}
		bqq.sql = prev
	}
	return nil
}

func (bqq *BRLQuoteQuery) sqlAll(ctx context.Context) ([]*BRLQuote, error) {
	var (
		nodes = []*BRLQuote{}
		_spec = bqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &BRLQuote{config: bqq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, bqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bqq *BRLQuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bqq.querySpec()
	_spec.Node.Columns = bqq.fields
	if len(bqq.fields) > 0 {
		_spec.Unique = bqq.unique != nil && *bqq.unique
	}
	return sqlgraph.CountNodes(ctx, bqq.driver, _spec)
}

func (bqq *BRLQuoteQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := bqq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (bqq *BRLQuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   brlquote.Table,
			Columns: brlquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: brlquote.FieldID,
			},
		},
		From:   bqq.sql,
		Unique: true,
	}
	if unique := bqq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := bqq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, brlquote.FieldID)
		for i := range fields {
			if fields[i] != brlquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bqq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bqq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bqq *BRLQuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bqq.driver.Dialect())
	t1 := builder.Table(brlquote.Table)
	columns := bqq.fields
	if len(columns) == 0 {
		columns = brlquote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bqq.sql != nil {
		selector = bqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bqq.unique != nil && *bqq.unique {
		selector.Distinct()
	}
	for _, p := range bqq.predicates {
		p(selector)
	}
	for _, p := range bqq.order {
		p(selector)
	}
	if offset := bqq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bqq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BRLQuoteGroupBy is the group-by builder for BRLQuote entities.
type BRLQuoteGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bqgb *BRLQuoteGroupBy) Aggregate(fns ...AggregateFunc) *BRLQuoteGroupBy {
	bqgb.fns = append(bqgb.fns, fns...)
	return bqgb
}

// Scan applies the group-by query and scans the result into the given value.
func (bqgb *BRLQuoteGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := bqgb.path(ctx)
	if err != nil {
		return err
	}
	bqgb.sql = query
	return bqgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := bqgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(bqgb.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := bqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) StringsX(ctx context.Context) []string {
	v, err := bqgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bqgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) StringX(ctx context.Context) string {
	v, err := bqgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(bqgb.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := bqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) IntsX(ctx context.Context) []int {
	v, err := bqgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bqgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) IntX(ctx context.Context) int {
	v, err := bqgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(bqgb.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := bqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := bqgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bqgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) Float64X(ctx context.Context) float64 {
	v, err := bqgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(bqgb.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := bqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := bqgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bqgb *BRLQuoteGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bqgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bqgb *BRLQuoteGroupBy) BoolX(ctx context.Context) bool {
	v, err := bqgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bqgb *BRLQuoteGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range bqgb.fields {
		if !brlquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := bqgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bqgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bqgb *BRLQuoteGroupBy) sqlQuery() *sql.Selector {
	selector := bqgb.sql.Select()
	aggregation := make([]string, 0, len(bqgb.fns))
	for _, fn := range bqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(bqgb.fields)+len(bqgb.fns))
		for _, f := range bqgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(bqgb.fields...)...)
}

// BRLQuoteSelect is the builder for selecting fields of BRLQuote entities.
type BRLQuoteSelect struct {
	*BRLQuoteQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (bqs *BRLQuoteSelect) Scan(ctx context.Context, v interface{}) error {
	if err := bqs.prepareQuery(ctx); err != nil {
		return err
	}
	bqs.sql = bqs.BRLQuoteQuery.sqlQuery(ctx)
	return bqs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bqs *BRLQuoteSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bqs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bqs.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bqs *BRLQuoteSelect) StringsX(ctx context.Context) []string {
	v, err := bqs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bqs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bqs *BRLQuoteSelect) StringX(ctx context.Context) string {
	v, err := bqs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bqs.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bqs *BRLQuoteSelect) IntsX(ctx context.Context) []int {
	v, err := bqs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bqs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bqs *BRLQuoteSelect) IntX(ctx context.Context) int {
	v, err := bqs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bqs.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bqs *BRLQuoteSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bqs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bqs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bqs *BRLQuoteSelect) Float64X(ctx context.Context) float64 {
	v, err := bqs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bqs.fields) > 1 {
		return nil, errors.New("ent: BRLQuoteSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bqs *BRLQuoteSelect) BoolsX(ctx context.Context) []bool {
	v, err := bqs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (bqs *BRLQuoteSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bqs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{brlquote.Label}
	default:
		err = fmt.Errorf("ent: BRLQuoteSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bqs *BRLQuoteSelect) BoolX(ctx context.Context) bool {
	v, err := bqs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bqs *BRLQuoteSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bqs.sql.Query()
	if err := bqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
