// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/btcquote"
	"main/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BTCQuoteUpdate is the builder for updating BTCQuote entities.
type BTCQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *BTCQuoteMutation
}

// Where appends a list predicates to the BTCQuoteUpdate builder.
func (bqu *BTCQuoteUpdate) Where(ps ...predicate.BTCQuote) *BTCQuoteUpdate {
	bqu.mutation.Where(ps...)
	return bqu
}

// SetPrice sets the "price" field.
func (bqu *BTCQuoteUpdate) SetPrice(f float64) *BTCQuoteUpdate {
	bqu.mutation.ResetPrice()
	bqu.mutation.SetPrice(f)
	return bqu
}

// AddPrice adds f to the "price" field.
func (bqu *BTCQuoteUpdate) AddPrice(f float64) *BTCQuoteUpdate {
	bqu.mutation.AddPrice(f)
	return bqu
}

// SetTimestamp sets the "Timestamp" field.
func (bqu *BTCQuoteUpdate) SetTimestamp(t time.Time) *BTCQuoteUpdate {
	bqu.mutation.SetTimestamp(t)
	return bqu
}

// Mutation returns the BTCQuoteMutation object of the builder.
func (bqu *BTCQuoteUpdate) Mutation() *BTCQuoteMutation {
	return bqu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bqu *BTCQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bqu.hooks) == 0 {
		affected, err = bqu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BTCQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bqu.mutation = mutation
			affected, err = bqu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bqu.hooks) - 1; i >= 0; i-- {
			if bqu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bqu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bqu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bqu *BTCQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := bqu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bqu *BTCQuoteUpdate) Exec(ctx context.Context) error {
	_, err := bqu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bqu *BTCQuoteUpdate) ExecX(ctx context.Context) {
	if err := bqu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bqu *BTCQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   btcquote.Table,
			Columns: btcquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: btcquote.FieldID,
			},
		},
	}
	if ps := bqu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bqu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: btcquote.FieldPrice,
		})
	}
	if value, ok := bqu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: btcquote.FieldPrice,
		})
	}
	if value, ok := bqu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: btcquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bqu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{btcquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// BTCQuoteUpdateOne is the builder for updating a single BTCQuote entity.
type BTCQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BTCQuoteMutation
}

// SetPrice sets the "price" field.
func (bquo *BTCQuoteUpdateOne) SetPrice(f float64) *BTCQuoteUpdateOne {
	bquo.mutation.ResetPrice()
	bquo.mutation.SetPrice(f)
	return bquo
}

// AddPrice adds f to the "price" field.
func (bquo *BTCQuoteUpdateOne) AddPrice(f float64) *BTCQuoteUpdateOne {
	bquo.mutation.AddPrice(f)
	return bquo
}

// SetTimestamp sets the "Timestamp" field.
func (bquo *BTCQuoteUpdateOne) SetTimestamp(t time.Time) *BTCQuoteUpdateOne {
	bquo.mutation.SetTimestamp(t)
	return bquo
}

// Mutation returns the BTCQuoteMutation object of the builder.
func (bquo *BTCQuoteUpdateOne) Mutation() *BTCQuoteMutation {
	return bquo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bquo *BTCQuoteUpdateOne) Select(field string, fields ...string) *BTCQuoteUpdateOne {
	bquo.fields = append([]string{field}, fields...)
	return bquo
}

// Save executes the query and returns the updated BTCQuote entity.
func (bquo *BTCQuoteUpdateOne) Save(ctx context.Context) (*BTCQuote, error) {
	var (
		err  error
		node *BTCQuote
	)
	if len(bquo.hooks) == 0 {
		node, err = bquo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BTCQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bquo.mutation = mutation
			node, err = bquo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bquo.hooks) - 1; i >= 0; i-- {
			if bquo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bquo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bquo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (bquo *BTCQuoteUpdateOne) SaveX(ctx context.Context) *BTCQuote {
	node, err := bquo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bquo *BTCQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := bquo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bquo *BTCQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := bquo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bquo *BTCQuoteUpdateOne) sqlSave(ctx context.Context) (_node *BTCQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   btcquote.Table,
			Columns: btcquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: btcquote.FieldID,
			},
		},
	}
	id, ok := bquo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BTCQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bquo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, btcquote.FieldID)
		for _, f := range fields {
			if !btcquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != btcquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bquo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bquo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: btcquote.FieldPrice,
		})
	}
	if value, ok := bquo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: btcquote.FieldPrice,
		})
	}
	if value, ok := bquo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: btcquote.FieldTimestamp,
		})
	}
	_node = &BTCQuote{config: bquo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bquo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{btcquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
