// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/cadquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// CADQuote is the model entity for the CADQuote schema.
type CADQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CADQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case cadquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case cadquote.FieldID:
			values[i] = new(sql.NullInt64)
		case cadquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CADQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CADQuote fields.
func (cq *CADQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cadquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cq.ID = int(value.Int64)
		case cadquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				cq.Price = value.Float64
			}
		case cadquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				cq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this CADQuote.
// Note that you need to call CADQuote.Unwrap() before calling this method if this CADQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (cq *CADQuote) Update() *CADQuoteUpdateOne {
	return (&CADQuoteClient{config: cq.config}).UpdateOne(cq)
}

// Unwrap unwraps the CADQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cq *CADQuote) Unwrap() *CADQuote {
	tx, ok := cq.config.driver.(*txDriver)
	if !ok {
		panic("ent: CADQuote is not a transactional entity")
	}
	cq.config.driver = tx.drv
	return cq
}

// String implements the fmt.Stringer.
func (cq *CADQuote) String() string {
	var builder strings.Builder
	builder.WriteString("CADQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", cq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", cq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(cq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CADQuotes is a parsable slice of CADQuote.
type CADQuotes []*CADQuote

func (cq CADQuotes) config(cfg config) {
	for _i := range cq {
		cq[_i].config = cfg
	}
}
