// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/clpquote"
	"main/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CLPQuoteUpdate is the builder for updating CLPQuote entities.
type CLPQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *CLPQuoteMutation
}

// Where appends a list predicates to the CLPQuoteUpdate builder.
func (cqu *CLPQuoteUpdate) Where(ps ...predicate.CLPQuote) *CLPQuoteUpdate {
	cqu.mutation.Where(ps...)
	return cqu
}

// SetPrice sets the "price" field.
func (cqu *CLPQuoteUpdate) SetPrice(f float64) *CLPQuoteUpdate {
	cqu.mutation.ResetPrice()
	cqu.mutation.SetPrice(f)
	return cqu
}

// AddPrice adds f to the "price" field.
func (cqu *CLPQuoteUpdate) AddPrice(f float64) *CLPQuoteUpdate {
	cqu.mutation.AddPrice(f)
	return cqu
}

// SetTimestamp sets the "Timestamp" field.
func (cqu *CLPQuoteUpdate) SetTimestamp(t time.Time) *CLPQuoteUpdate {
	cqu.mutation.SetTimestamp(t)
	return cqu
}

// Mutation returns the CLPQuoteMutation object of the builder.
func (cqu *CLPQuoteUpdate) Mutation() *CLPQuoteMutation {
	return cqu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cqu *CLPQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cqu.hooks) == 0 {
		affected, err = cqu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CLPQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cqu.mutation = mutation
			affected, err = cqu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cqu.hooks) - 1; i >= 0; i-- {
			if cqu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cqu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cqu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cqu *CLPQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := cqu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cqu *CLPQuoteUpdate) Exec(ctx context.Context) error {
	_, err := cqu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cqu *CLPQuoteUpdate) ExecX(ctx context.Context) {
	if err := cqu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cqu *CLPQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   clpquote.Table,
			Columns: clpquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clpquote.FieldID,
			},
		},
	}
	if ps := cqu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cqu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: clpquote.FieldPrice,
		})
	}
	if value, ok := cqu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: clpquote.FieldPrice,
		})
	}
	if value, ok := cqu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: clpquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cqu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clpquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CLPQuoteUpdateOne is the builder for updating a single CLPQuote entity.
type CLPQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CLPQuoteMutation
}

// SetPrice sets the "price" field.
func (cquo *CLPQuoteUpdateOne) SetPrice(f float64) *CLPQuoteUpdateOne {
	cquo.mutation.ResetPrice()
	cquo.mutation.SetPrice(f)
	return cquo
}

// AddPrice adds f to the "price" field.
func (cquo *CLPQuoteUpdateOne) AddPrice(f float64) *CLPQuoteUpdateOne {
	cquo.mutation.AddPrice(f)
	return cquo
}

// SetTimestamp sets the "Timestamp" field.
func (cquo *CLPQuoteUpdateOne) SetTimestamp(t time.Time) *CLPQuoteUpdateOne {
	cquo.mutation.SetTimestamp(t)
	return cquo
}

// Mutation returns the CLPQuoteMutation object of the builder.
func (cquo *CLPQuoteUpdateOne) Mutation() *CLPQuoteMutation {
	return cquo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cquo *CLPQuoteUpdateOne) Select(field string, fields ...string) *CLPQuoteUpdateOne {
	cquo.fields = append([]string{field}, fields...)
	return cquo
}

// Save executes the query and returns the updated CLPQuote entity.
func (cquo *CLPQuoteUpdateOne) Save(ctx context.Context) (*CLPQuote, error) {
	var (
		err  error
		node *CLPQuote
	)
	if len(cquo.hooks) == 0 {
		node, err = cquo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CLPQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cquo.mutation = mutation
			node, err = cquo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cquo.hooks) - 1; i >= 0; i-- {
			if cquo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cquo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cquo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cquo *CLPQuoteUpdateOne) SaveX(ctx context.Context) *CLPQuote {
	node, err := cquo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cquo *CLPQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := cquo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cquo *CLPQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := cquo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cquo *CLPQuoteUpdateOne) sqlSave(ctx context.Context) (_node *CLPQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   clpquote.Table,
			Columns: clpquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clpquote.FieldID,
			},
		},
	}
	id, ok := cquo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CLPQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cquo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clpquote.FieldID)
		for _, f := range fields {
			if !clpquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clpquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cquo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cquo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: clpquote.FieldPrice,
		})
	}
	if value, ok := cquo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: clpquote.FieldPrice,
		})
	}
	if value, ok := cquo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: clpquote.FieldTimestamp,
		})
	}
	_node = &CLPQuote{config: cquo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cquo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clpquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
