// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/czkquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// CZKQuote is the model entity for the CZKQuote schema.
type CZKQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CZKQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case czkquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case czkquote.FieldID:
			values[i] = new(sql.NullInt64)
		case czkquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CZKQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CZKQuote fields.
func (cq *CZKQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case czkquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cq.ID = int(value.Int64)
		case czkquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				cq.Price = value.Float64
			}
		case czkquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				cq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this CZKQuote.
// Note that you need to call CZKQuote.Unwrap() before calling this method if this CZKQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (cq *CZKQuote) Update() *CZKQuoteUpdateOne {
	return (&CZKQuoteClient{config: cq.config}).UpdateOne(cq)
}

// Unwrap unwraps the CZKQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cq *CZKQuote) Unwrap() *CZKQuote {
	tx, ok := cq.config.driver.(*txDriver)
	if !ok {
		panic("ent: CZKQuote is not a transactional entity")
	}
	cq.config.driver = tx.drv
	return cq
}

// String implements the fmt.Stringer.
func (cq *CZKQuote) String() string {
	var builder strings.Builder
	builder.WriteString("CZKQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", cq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", cq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(cq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CZKQuotes is a parsable slice of CZKQuote.
type CZKQuotes []*CZKQuote

func (cq CZKQuotes) config(cfg config) {
	for _i := range cq {
		cq[_i].config = cfg
	}
}
