// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/euroquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// EUROQuote is the model entity for the EUROQuote schema.
type EUROQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EUROQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case euroquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case euroquote.FieldID:
			values[i] = new(sql.NullInt64)
		case euroquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EUROQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EUROQuote fields.
func (eq *EUROQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case euroquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			eq.ID = int(value.Int64)
		case euroquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				eq.Price = value.Float64
			}
		case euroquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				eq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this EUROQuote.
// Note that you need to call EUROQuote.Unwrap() before calling this method if this EUROQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (eq *EUROQuote) Update() *EUROQuoteUpdateOne {
	return (&EUROQuoteClient{config: eq.config}).UpdateOne(eq)
}

// Unwrap unwraps the EUROQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (eq *EUROQuote) Unwrap() *EUROQuote {
	tx, ok := eq.config.driver.(*txDriver)
	if !ok {
		panic("ent: EUROQuote is not a transactional entity")
	}
	eq.config.driver = tx.drv
	return eq
}

// String implements the fmt.Stringer.
func (eq *EUROQuote) String() string {
	var builder strings.Builder
	builder.WriteString("EUROQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", eq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", eq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(eq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EUROQuotes is a parsable slice of EUROQuote.
type EUROQuotes []*EUROQuote

func (eq EUROQuotes) config(cfg config) {
	for _i := range eq {
		eq[_i].config = cfg
	}
}
