// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/euroquote"
	"main/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EUROQuoteDelete is the builder for deleting a EUROQuote entity.
type EUROQuoteDelete struct {
	config
	hooks    []Hook
	mutation *EUROQuoteMutation
}

// Where appends a list predicates to the EUROQuoteDelete builder.
func (eqd *EUROQuoteDelete) Where(ps ...predicate.EUROQuote) *EUROQuoteDelete {
	eqd.mutation.Where(ps...)
	return eqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eqd *EUROQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eqd.hooks) == 0 {
		affected, err = eqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EUROQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eqd.mutation = mutation
			affected, err = eqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eqd.hooks) - 1; i >= 0; i-- {
			if eqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (eqd *EUROQuoteDelete) ExecX(ctx context.Context) int {
	n, err := eqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eqd *EUROQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: euroquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: euroquote.FieldID,
			},
		},
	}
	if ps := eqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, eqd.driver, _spec)
}

// EUROQuoteDeleteOne is the builder for deleting a single EUROQuote entity.
type EUROQuoteDeleteOne struct {
	eqd *EUROQuoteDelete
}

// Exec executes the deletion query.
func (eqdo *EUROQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := eqdo.eqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{euroquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eqdo *EUROQuoteDeleteOne) ExecX(ctx context.Context) {
	eqdo.eqd.ExecX(ctx)
}
