// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/gbpquote"
	"main/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GBPQuoteUpdate is the builder for updating GBPQuote entities.
type GBPQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *GBPQuoteMutation
}

// Where appends a list predicates to the GBPQuoteUpdate builder.
func (gqu *GBPQuoteUpdate) Where(ps ...predicate.GBPQuote) *GBPQuoteUpdate {
	gqu.mutation.Where(ps...)
	return gqu
}

// SetPrice sets the "price" field.
func (gqu *GBPQuoteUpdate) SetPrice(f float64) *GBPQuoteUpdate {
	gqu.mutation.ResetPrice()
	gqu.mutation.SetPrice(f)
	return gqu
}

// AddPrice adds f to the "price" field.
func (gqu *GBPQuoteUpdate) AddPrice(f float64) *GBPQuoteUpdate {
	gqu.mutation.AddPrice(f)
	return gqu
}

// SetTimestamp sets the "Timestamp" field.
func (gqu *GBPQuoteUpdate) SetTimestamp(t time.Time) *GBPQuoteUpdate {
	gqu.mutation.SetTimestamp(t)
	return gqu
}

// Mutation returns the GBPQuoteMutation object of the builder.
func (gqu *GBPQuoteUpdate) Mutation() *GBPQuoteMutation {
	return gqu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gqu *GBPQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gqu.hooks) == 0 {
		affected, err = gqu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GBPQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gqu.mutation = mutation
			affected, err = gqu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gqu.hooks) - 1; i >= 0; i-- {
			if gqu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gqu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gqu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (gqu *GBPQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := gqu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gqu *GBPQuoteUpdate) Exec(ctx context.Context) error {
	_, err := gqu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gqu *GBPQuoteUpdate) ExecX(ctx context.Context) {
	if err := gqu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gqu *GBPQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gbpquote.Table,
			Columns: gbpquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gbpquote.FieldID,
			},
		},
	}
	if ps := gqu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gqu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: gbpquote.FieldPrice,
		})
	}
	if value, ok := gqu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: gbpquote.FieldPrice,
		})
	}
	if value, ok := gqu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: gbpquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gqu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gbpquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// GBPQuoteUpdateOne is the builder for updating a single GBPQuote entity.
type GBPQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GBPQuoteMutation
}

// SetPrice sets the "price" field.
func (gquo *GBPQuoteUpdateOne) SetPrice(f float64) *GBPQuoteUpdateOne {
	gquo.mutation.ResetPrice()
	gquo.mutation.SetPrice(f)
	return gquo
}

// AddPrice adds f to the "price" field.
func (gquo *GBPQuoteUpdateOne) AddPrice(f float64) *GBPQuoteUpdateOne {
	gquo.mutation.AddPrice(f)
	return gquo
}

// SetTimestamp sets the "Timestamp" field.
func (gquo *GBPQuoteUpdateOne) SetTimestamp(t time.Time) *GBPQuoteUpdateOne {
	gquo.mutation.SetTimestamp(t)
	return gquo
}

// Mutation returns the GBPQuoteMutation object of the builder.
func (gquo *GBPQuoteUpdateOne) Mutation() *GBPQuoteMutation {
	return gquo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (gquo *GBPQuoteUpdateOne) Select(field string, fields ...string) *GBPQuoteUpdateOne {
	gquo.fields = append([]string{field}, fields...)
	return gquo
}

// Save executes the query and returns the updated GBPQuote entity.
func (gquo *GBPQuoteUpdateOne) Save(ctx context.Context) (*GBPQuote, error) {
	var (
		err  error
		node *GBPQuote
	)
	if len(gquo.hooks) == 0 {
		node, err = gquo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GBPQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gquo.mutation = mutation
			node, err = gquo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(gquo.hooks) - 1; i >= 0; i-- {
			if gquo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gquo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gquo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (gquo *GBPQuoteUpdateOne) SaveX(ctx context.Context) *GBPQuote {
	node, err := gquo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (gquo *GBPQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := gquo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gquo *GBPQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := gquo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gquo *GBPQuoteUpdateOne) sqlSave(ctx context.Context) (_node *GBPQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gbpquote.Table,
			Columns: gbpquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gbpquote.FieldID,
			},
		},
	}
	id, ok := gquo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GBPQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := gquo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gbpquote.FieldID)
		for _, f := range fields {
			if !gbpquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gbpquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := gquo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gquo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: gbpquote.FieldPrice,
		})
	}
	if value, ok := gquo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: gbpquote.FieldPrice,
		})
	}
	if value, ok := gquo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: gbpquote.FieldTimestamp,
		})
	}
	_node = &GBPQuote{config: gquo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, gquo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gbpquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
