// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/gbpquote"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GBPQuoteCreate is the builder for creating a GBPQuote entity.
type GBPQuoteCreate struct {
	config
	mutation *GBPQuoteMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (gqc *GBPQuoteCreate) SetPrice(f float64) *GBPQuoteCreate {
	gqc.mutation.SetPrice(f)
	return gqc
}

// SetTimestamp sets the "Timestamp" field.
func (gqc *GBPQuoteCreate) SetTimestamp(t time.Time) *GBPQuoteCreate {
	gqc.mutation.SetTimestamp(t)
	return gqc
}

// SetID sets the "id" field.
func (gqc *GBPQuoteCreate) SetID(i int) *GBPQuoteCreate {
	gqc.mutation.SetID(i)
	return gqc
}

// Mutation returns the GBPQuoteMutation object of the builder.
func (gqc *GBPQuoteCreate) Mutation() *GBPQuoteMutation {
	return gqc.mutation
}

// Save creates the GBPQuote in the database.
func (gqc *GBPQuoteCreate) Save(ctx context.Context) (*GBPQuote, error) {
	var (
		err  error
		node *GBPQuote
	)
	if len(gqc.hooks) == 0 {
		if err = gqc.check(); err != nil {
			return nil, err
		}
		node, err = gqc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GBPQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gqc.check(); err != nil {
				return nil, err
			}
			gqc.mutation = mutation
			if node, err = gqc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gqc.hooks) - 1; i >= 0; i-- {
			if gqc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gqc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gqc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gqc *GBPQuoteCreate) SaveX(ctx context.Context) *GBPQuote {
	v, err := gqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gqc *GBPQuoteCreate) Exec(ctx context.Context) error {
	_, err := gqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gqc *GBPQuoteCreate) ExecX(ctx context.Context) {
	if err := gqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gqc *GBPQuoteCreate) check() error {
	if _, ok := gqc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "GBPQuote.price"`)}
	}
	if _, ok := gqc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "Timestamp", err: errors.New(`ent: missing required field "GBPQuote.Timestamp"`)}
	}
	return nil
}

func (gqc *GBPQuoteCreate) sqlSave(ctx context.Context) (*GBPQuote, error) {
	_node, _spec := gqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (gqc *GBPQuoteCreate) createSpec() (*GBPQuote, *sqlgraph.CreateSpec) {
	var (
		_node = &GBPQuote{config: gqc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: gbpquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gbpquote.FieldID,
			},
		}
	)
	if id, ok := gqc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := gqc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: gbpquote.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := gqc.mutation.Timestamp(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: gbpquote.FieldTimestamp,
		})
		_node.Timestamp = value
	}
	return _node, _spec
}

// GBPQuoteCreateBulk is the builder for creating many GBPQuote entities in bulk.
type GBPQuoteCreateBulk struct {
	config
	builders []*GBPQuoteCreate
}

// Save creates the GBPQuote entities in the database.
func (gqcb *GBPQuoteCreateBulk) Save(ctx context.Context) ([]*GBPQuote, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gqcb.builders))
	nodes := make([]*GBPQuote, len(gqcb.builders))
	mutators := make([]Mutator, len(gqcb.builders))
	for i := range gqcb.builders {
		func(i int, root context.Context) {
			builder := gqcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GBPQuoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gqcb *GBPQuoteCreateBulk) SaveX(ctx context.Context) []*GBPQuote {
	v, err := gqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gqcb *GBPQuoteCreateBulk) Exec(ctx context.Context) error {
	_, err := gqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gqcb *GBPQuoteCreateBulk) ExecX(ctx context.Context) {
	if err := gqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
