// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/hufquote"
	"main/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HUFQuoteDelete is the builder for deleting a HUFQuote entity.
type HUFQuoteDelete struct {
	config
	hooks    []Hook
	mutation *HUFQuoteMutation
}

// Where appends a list predicates to the HUFQuoteDelete builder.
func (hqd *HUFQuoteDelete) Where(ps ...predicate.HUFQuote) *HUFQuoteDelete {
	hqd.mutation.Where(ps...)
	return hqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hqd *HUFQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(hqd.hooks) == 0 {
		affected, err = hqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HUFQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hqd.mutation = mutation
			affected, err = hqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(hqd.hooks) - 1; i >= 0; i-- {
			if hqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (hqd *HUFQuoteDelete) ExecX(ctx context.Context) int {
	n, err := hqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hqd *HUFQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: hufquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: hufquote.FieldID,
			},
		},
	}
	if ps := hqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, hqd.driver, _spec)
}

// HUFQuoteDeleteOne is the builder for deleting a single HUFQuote entity.
type HUFQuoteDeleteOne struct {
	hqd *HUFQuoteDelete
}

// Exec executes the deletion query.
func (hqdo *HUFQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := hqdo.hqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hufquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hqdo *HUFQuoteDeleteOne) ExecX(ctx context.Context) {
	hqdo.hqd.ExecX(ctx)
}
