// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/idrquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// IDRQuote is the model entity for the IDRQuote schema.
type IDRQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IDRQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case idrquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case idrquote.FieldID:
			values[i] = new(sql.NullInt64)
		case idrquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type IDRQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IDRQuote fields.
func (iq *IDRQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case idrquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			iq.ID = int(value.Int64)
		case idrquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				iq.Price = value.Float64
			}
		case idrquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				iq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this IDRQuote.
// Note that you need to call IDRQuote.Unwrap() before calling this method if this IDRQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (iq *IDRQuote) Update() *IDRQuoteUpdateOne {
	return (&IDRQuoteClient{config: iq.config}).UpdateOne(iq)
}

// Unwrap unwraps the IDRQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (iq *IDRQuote) Unwrap() *IDRQuote {
	tx, ok := iq.config.driver.(*txDriver)
	if !ok {
		panic("ent: IDRQuote is not a transactional entity")
	}
	iq.config.driver = tx.drv
	return iq
}

// String implements the fmt.Stringer.
func (iq *IDRQuote) String() string {
	var builder strings.Builder
	builder.WriteString("IDRQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", iq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", iq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(iq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IDRQuotes is a parsable slice of IDRQuote.
type IDRQuotes []*IDRQuote

func (iq IDRQuotes) config(cfg config) {
	for _i := range iq {
		iq[_i].config = cfg
	}
}
