// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/ilsquote"
	"main/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ILSQuoteUpdate is the builder for updating ILSQuote entities.
type ILSQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *ILSQuoteMutation
}

// Where appends a list predicates to the ILSQuoteUpdate builder.
func (iqu *ILSQuoteUpdate) Where(ps ...predicate.ILSQuote) *ILSQuoteUpdate {
	iqu.mutation.Where(ps...)
	return iqu
}

// SetPrice sets the "price" field.
func (iqu *ILSQuoteUpdate) SetPrice(f float64) *ILSQuoteUpdate {
	iqu.mutation.ResetPrice()
	iqu.mutation.SetPrice(f)
	return iqu
}

// AddPrice adds f to the "price" field.
func (iqu *ILSQuoteUpdate) AddPrice(f float64) *ILSQuoteUpdate {
	iqu.mutation.AddPrice(f)
	return iqu
}

// SetTimestamp sets the "Timestamp" field.
func (iqu *ILSQuoteUpdate) SetTimestamp(t time.Time) *ILSQuoteUpdate {
	iqu.mutation.SetTimestamp(t)
	return iqu
}

// Mutation returns the ILSQuoteMutation object of the builder.
func (iqu *ILSQuoteUpdate) Mutation() *ILSQuoteMutation {
	return iqu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iqu *ILSQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iqu.hooks) == 0 {
		affected, err = iqu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ILSQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iqu.mutation = mutation
			affected, err = iqu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iqu.hooks) - 1; i >= 0; i-- {
			if iqu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iqu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iqu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (iqu *ILSQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := iqu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iqu *ILSQuoteUpdate) Exec(ctx context.Context) error {
	_, err := iqu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iqu *ILSQuoteUpdate) ExecX(ctx context.Context) {
	if err := iqu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iqu *ILSQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ilsquote.Table,
			Columns: ilsquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ilsquote.FieldID,
			},
		},
	}
	if ps := iqu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iqu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: ilsquote.FieldPrice,
		})
	}
	if value, ok := iqu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: ilsquote.FieldPrice,
		})
	}
	if value, ok := iqu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ilsquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iqu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ilsquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ILSQuoteUpdateOne is the builder for updating a single ILSQuote entity.
type ILSQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ILSQuoteMutation
}

// SetPrice sets the "price" field.
func (iquo *ILSQuoteUpdateOne) SetPrice(f float64) *ILSQuoteUpdateOne {
	iquo.mutation.ResetPrice()
	iquo.mutation.SetPrice(f)
	return iquo
}

// AddPrice adds f to the "price" field.
func (iquo *ILSQuoteUpdateOne) AddPrice(f float64) *ILSQuoteUpdateOne {
	iquo.mutation.AddPrice(f)
	return iquo
}

// SetTimestamp sets the "Timestamp" field.
func (iquo *ILSQuoteUpdateOne) SetTimestamp(t time.Time) *ILSQuoteUpdateOne {
	iquo.mutation.SetTimestamp(t)
	return iquo
}

// Mutation returns the ILSQuoteMutation object of the builder.
func (iquo *ILSQuoteUpdateOne) Mutation() *ILSQuoteMutation {
	return iquo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iquo *ILSQuoteUpdateOne) Select(field string, fields ...string) *ILSQuoteUpdateOne {
	iquo.fields = append([]string{field}, fields...)
	return iquo
}

// Save executes the query and returns the updated ILSQuote entity.
func (iquo *ILSQuoteUpdateOne) Save(ctx context.Context) (*ILSQuote, error) {
	var (
		err  error
		node *ILSQuote
	)
	if len(iquo.hooks) == 0 {
		node, err = iquo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ILSQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iquo.mutation = mutation
			node, err = iquo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(iquo.hooks) - 1; i >= 0; i-- {
			if iquo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iquo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iquo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (iquo *ILSQuoteUpdateOne) SaveX(ctx context.Context) *ILSQuote {
	node, err := iquo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iquo *ILSQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := iquo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iquo *ILSQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := iquo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iquo *ILSQuoteUpdateOne) sqlSave(ctx context.Context) (_node *ILSQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ilsquote.Table,
			Columns: ilsquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ilsquote.FieldID,
			},
		},
	}
	id, ok := iquo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ILSQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iquo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ilsquote.FieldID)
		for _, f := range fields {
			if !ilsquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ilsquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iquo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iquo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: ilsquote.FieldPrice,
		})
	}
	if value, ok := iquo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: ilsquote.FieldPrice,
		})
	}
	if value, ok := iquo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ilsquote.FieldTimestamp,
		})
	}
	_node = &ILSQuote{config: iquo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iquo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ilsquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
