// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/inrquote"
	"main/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// INRQuoteQuery is the builder for querying INRQuote entities.
type INRQuoteQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.INRQuote
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the INRQuoteQuery builder.
func (iqq *INRQuoteQuery) Where(ps ...predicate.INRQuote) *INRQuoteQuery {
	iqq.predicates = append(iqq.predicates, ps...)
	return iqq
}

// Limit adds a limit step to the query.
func (iqq *INRQuoteQuery) Limit(limit int) *INRQuoteQuery {
	iqq.limit = &limit
	return iqq
}

// Offset adds an offset step to the query.
func (iqq *INRQuoteQuery) Offset(offset int) *INRQuoteQuery {
	iqq.offset = &offset
	return iqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iqq *INRQuoteQuery) Unique(unique bool) *INRQuoteQuery {
	iqq.unique = &unique
	return iqq
}

// Order adds an order step to the query.
func (iqq *INRQuoteQuery) Order(o ...OrderFunc) *INRQuoteQuery {
	iqq.order = append(iqq.order, o...)
	return iqq
}

// First returns the first INRQuote entity from the query.
// Returns a *NotFoundError when no INRQuote was found.
func (iqq *INRQuoteQuery) First(ctx context.Context) (*INRQuote, error) {
	nodes, err := iqq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{inrquote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iqq *INRQuoteQuery) FirstX(ctx context.Context) *INRQuote {
	node, err := iqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first INRQuote ID from the query.
// Returns a *NotFoundError when no INRQuote ID was found.
func (iqq *INRQuoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iqq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{inrquote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iqq *INRQuoteQuery) FirstIDX(ctx context.Context) int {
	id, err := iqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single INRQuote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one INRQuote entity is found.
// Returns a *NotFoundError when no INRQuote entities are found.
func (iqq *INRQuoteQuery) Only(ctx context.Context) (*INRQuote, error) {
	nodes, err := iqq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{inrquote.Label}
	default:
		return nil, &NotSingularError{inrquote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iqq *INRQuoteQuery) OnlyX(ctx context.Context) *INRQuote {
	node, err := iqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only INRQuote ID in the query.
// Returns a *NotSingularError when more than one INRQuote ID is found.
// Returns a *NotFoundError when no entities are found.
func (iqq *INRQuoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iqq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = &NotSingularError{inrquote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iqq *INRQuoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := iqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of INRQuotes.
func (iqq *INRQuoteQuery) All(ctx context.Context) ([]*INRQuote, error) {
	if err := iqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return iqq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (iqq *INRQuoteQuery) AllX(ctx context.Context) []*INRQuote {
	nodes, err := iqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of INRQuote IDs.
func (iqq *INRQuoteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := iqq.Select(inrquote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iqq *INRQuoteQuery) IDsX(ctx context.Context) []int {
	ids, err := iqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iqq *INRQuoteQuery) Count(ctx context.Context) (int, error) {
	if err := iqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return iqq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (iqq *INRQuoteQuery) CountX(ctx context.Context) int {
	count, err := iqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iqq *INRQuoteQuery) Exist(ctx context.Context) (bool, error) {
	if err := iqq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return iqq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (iqq *INRQuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := iqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the INRQuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iqq *INRQuoteQuery) Clone() *INRQuoteQuery {
	if iqq == nil {
		return nil
	}
	return &INRQuoteQuery{
		config:     iqq.config,
		limit:      iqq.limit,
		offset:     iqq.offset,
		order:      append([]OrderFunc{}, iqq.order...),
		predicates: append([]predicate.INRQuote{}, iqq.predicates...),
		// clone intermediate query.
		sql:    iqq.sql.Clone(),
		path:   iqq.path,
		unique: iqq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.INRQuote.Query().
//		GroupBy(inrquote.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (iqq *INRQuoteQuery) GroupBy(field string, fields ...string) *INRQuoteGroupBy {
	group := &INRQuoteGroupBy{config: iqq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := iqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return iqq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.INRQuote.Query().
//		Select(inrquote.FieldPrice).
//		Scan(ctx, &v)
//
func (iqq *INRQuoteQuery) Select(fields ...string) *INRQuoteSelect {
	iqq.fields = append(iqq.fields, fields...)
	return &INRQuoteSelect{INRQuoteQuery: iqq}
}

func (iqq *INRQuoteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range iqq.fields {
		if !inrquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iqq.path != nil {
		prev, err := iqq.path(ctx)
		if err != nil {
			return err
		}
		iqq.sql = prev
	}
	return nil
}

func (iqq *INRQuoteQuery) sqlAll(ctx context.Context) ([]*INRQuote, error) {
	var (
		nodes = []*INRQuote{}
		_spec = iqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &INRQuote{config: iqq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, iqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (iqq *INRQuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iqq.querySpec()
	_spec.Node.Columns = iqq.fields
	if len(iqq.fields) > 0 {
		_spec.Unique = iqq.unique != nil && *iqq.unique
	}
	return sqlgraph.CountNodes(ctx, iqq.driver, _spec)
}

func (iqq *INRQuoteQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := iqq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (iqq *INRQuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   inrquote.Table,
			Columns: inrquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: inrquote.FieldID,
			},
		},
		From:   iqq.sql,
		Unique: true,
	}
	if unique := iqq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := iqq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inrquote.FieldID)
		for i := range fields {
			if fields[i] != inrquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iqq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iqq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iqq *INRQuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iqq.driver.Dialect())
	t1 := builder.Table(inrquote.Table)
	columns := iqq.fields
	if len(columns) == 0 {
		columns = inrquote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iqq.sql != nil {
		selector = iqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iqq.unique != nil && *iqq.unique {
		selector.Distinct()
	}
	for _, p := range iqq.predicates {
		p(selector)
	}
	for _, p := range iqq.order {
		p(selector)
	}
	if offset := iqq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iqq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// INRQuoteGroupBy is the group-by builder for INRQuote entities.
type INRQuoteGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iqgb *INRQuoteGroupBy) Aggregate(fns ...AggregateFunc) *INRQuoteGroupBy {
	iqgb.fns = append(iqgb.fns, fns...)
	return iqgb
}

// Scan applies the group-by query and scans the result into the given value.
func (iqgb *INRQuoteGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := iqgb.path(ctx)
	if err != nil {
		return err
	}
	iqgb.sql = query
	return iqgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := iqgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(iqgb.fields) > 1 {
		return nil, errors.New("ent: INRQuoteGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := iqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) StringsX(ctx context.Context) []string {
	v, err := iqgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = iqgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) StringX(ctx context.Context) string {
	v, err := iqgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(iqgb.fields) > 1 {
		return nil, errors.New("ent: INRQuoteGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := iqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) IntsX(ctx context.Context) []int {
	v, err := iqgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = iqgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) IntX(ctx context.Context) int {
	v, err := iqgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(iqgb.fields) > 1 {
		return nil, errors.New("ent: INRQuoteGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := iqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := iqgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = iqgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) Float64X(ctx context.Context) float64 {
	v, err := iqgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(iqgb.fields) > 1 {
		return nil, errors.New("ent: INRQuoteGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := iqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := iqgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iqgb *INRQuoteGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = iqgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (iqgb *INRQuoteGroupBy) BoolX(ctx context.Context) bool {
	v, err := iqgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (iqgb *INRQuoteGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range iqgb.fields {
		if !inrquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := iqgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iqgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (iqgb *INRQuoteGroupBy) sqlQuery() *sql.Selector {
	selector := iqgb.sql.Select()
	aggregation := make([]string, 0, len(iqgb.fns))
	for _, fn := range iqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(iqgb.fields)+len(iqgb.fns))
		for _, f := range iqgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(iqgb.fields...)...)
}

// INRQuoteSelect is the builder for selecting fields of INRQuote entities.
type INRQuoteSelect struct {
	*INRQuoteQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (iqs *INRQuoteSelect) Scan(ctx context.Context, v interface{}) error {
	if err := iqs.prepareQuery(ctx); err != nil {
		return err
	}
	iqs.sql = iqs.INRQuoteQuery.sqlQuery(ctx)
	return iqs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (iqs *INRQuoteSelect) ScanX(ctx context.Context, v interface{}) {
	if err := iqs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Strings(ctx context.Context) ([]string, error) {
	if len(iqs.fields) > 1 {
		return nil, errors.New("ent: INRQuoteSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := iqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (iqs *INRQuoteSelect) StringsX(ctx context.Context) []string {
	v, err := iqs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = iqs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (iqs *INRQuoteSelect) StringX(ctx context.Context) string {
	v, err := iqs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Ints(ctx context.Context) ([]int, error) {
	if len(iqs.fields) > 1 {
		return nil, errors.New("ent: INRQuoteSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := iqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (iqs *INRQuoteSelect) IntsX(ctx context.Context) []int {
	v, err := iqs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = iqs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (iqs *INRQuoteSelect) IntX(ctx context.Context) int {
	v, err := iqs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(iqs.fields) > 1 {
		return nil, errors.New("ent: INRQuoteSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := iqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (iqs *INRQuoteSelect) Float64sX(ctx context.Context) []float64 {
	v, err := iqs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = iqs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (iqs *INRQuoteSelect) Float64X(ctx context.Context) float64 {
	v, err := iqs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(iqs.fields) > 1 {
		return nil, errors.New("ent: INRQuoteSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := iqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (iqs *INRQuoteSelect) BoolsX(ctx context.Context) []bool {
	v, err := iqs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (iqs *INRQuoteSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = iqs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{inrquote.Label}
	default:
		err = fmt.Errorf("ent: INRQuoteSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (iqs *INRQuoteSelect) BoolX(ctx context.Context) bool {
	v, err := iqs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (iqs *INRQuoteSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := iqs.sql.Query()
	if err := iqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
