// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/mxnquote"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MXNQuoteCreate is the builder for creating a MXNQuote entity.
type MXNQuoteCreate struct {
	config
	mutation *MXNQuoteMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (mqc *MXNQuoteCreate) SetPrice(f float64) *MXNQuoteCreate {
	mqc.mutation.SetPrice(f)
	return mqc
}

// SetTimestamp sets the "Timestamp" field.
func (mqc *MXNQuoteCreate) SetTimestamp(t time.Time) *MXNQuoteCreate {
	mqc.mutation.SetTimestamp(t)
	return mqc
}

// SetID sets the "id" field.
func (mqc *MXNQuoteCreate) SetID(i int) *MXNQuoteCreate {
	mqc.mutation.SetID(i)
	return mqc
}

// Mutation returns the MXNQuoteMutation object of the builder.
func (mqc *MXNQuoteCreate) Mutation() *MXNQuoteMutation {
	return mqc.mutation
}

// Save creates the MXNQuote in the database.
func (mqc *MXNQuoteCreate) Save(ctx context.Context) (*MXNQuote, error) {
	var (
		err  error
		node *MXNQuote
	)
	if len(mqc.hooks) == 0 {
		if err = mqc.check(); err != nil {
			return nil, err
		}
		node, err = mqc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MXNQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mqc.check(); err != nil {
				return nil, err
			}
			mqc.mutation = mutation
			if node, err = mqc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mqc.hooks) - 1; i >= 0; i-- {
			if mqc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mqc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mqc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mqc *MXNQuoteCreate) SaveX(ctx context.Context) *MXNQuote {
	v, err := mqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mqc *MXNQuoteCreate) Exec(ctx context.Context) error {
	_, err := mqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mqc *MXNQuoteCreate) ExecX(ctx context.Context) {
	if err := mqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mqc *MXNQuoteCreate) check() error {
	if _, ok := mqc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "MXNQuote.price"`)}
	}
	if _, ok := mqc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "Timestamp", err: errors.New(`ent: missing required field "MXNQuote.Timestamp"`)}
	}
	return nil
}

func (mqc *MXNQuoteCreate) sqlSave(ctx context.Context) (*MXNQuote, error) {
	_node, _spec := mqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (mqc *MXNQuoteCreate) createSpec() (*MXNQuote, *sqlgraph.CreateSpec) {
	var (
		_node = &MXNQuote{config: mqc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: mxnquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mxnquote.FieldID,
			},
		}
	)
	if id, ok := mqc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := mqc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: mxnquote.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := mqc.mutation.Timestamp(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: mxnquote.FieldTimestamp,
		})
		_node.Timestamp = value
	}
	return _node, _spec
}

// MXNQuoteCreateBulk is the builder for creating many MXNQuote entities in bulk.
type MXNQuoteCreateBulk struct {
	config
	builders []*MXNQuoteCreate
}

// Save creates the MXNQuote entities in the database.
func (mqcb *MXNQuoteCreateBulk) Save(ctx context.Context) ([]*MXNQuote, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mqcb.builders))
	nodes := make([]*MXNQuote, len(mqcb.builders))
	mutators := make([]Mutator, len(mqcb.builders))
	for i := range mqcb.builders {
		func(i int, root context.Context) {
			builder := mqcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MXNQuoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mqcb *MXNQuoteCreateBulk) SaveX(ctx context.Context) []*MXNQuote {
	v, err := mqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mqcb *MXNQuoteCreateBulk) Exec(ctx context.Context) error {
	_, err := mqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mqcb *MXNQuoteCreateBulk) ExecX(ctx context.Context) {
	if err := mqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
