// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/mxnquote"
	"main/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MXNQuoteDelete is the builder for deleting a MXNQuote entity.
type MXNQuoteDelete struct {
	config
	hooks    []Hook
	mutation *MXNQuoteMutation
}

// Where appends a list predicates to the MXNQuoteDelete builder.
func (mqd *MXNQuoteDelete) Where(ps ...predicate.MXNQuote) *MXNQuoteDelete {
	mqd.mutation.Where(ps...)
	return mqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mqd *MXNQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mqd.hooks) == 0 {
		affected, err = mqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MXNQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mqd.mutation = mutation
			affected, err = mqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mqd.hooks) - 1; i >= 0; i-- {
			if mqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mqd *MXNQuoteDelete) ExecX(ctx context.Context) int {
	n, err := mqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mqd *MXNQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mxnquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mxnquote.FieldID,
			},
		},
	}
	if ps := mqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mqd.driver, _spec)
}

// MXNQuoteDeleteOne is the builder for deleting a single MXNQuote entity.
type MXNQuoteDeleteOne struct {
	mqd *MXNQuoteDelete
}

// Exec executes the deletion query.
func (mqdo *MXNQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := mqdo.mqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mxnquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mqdo *MXNQuoteDeleteOne) ExecX(ctx context.Context) {
	mqdo.mqd.ExecX(ctx)
}
