// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/nokquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// NOKQuote is the model entity for the NOKQuote schema.
type NOKQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NOKQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case nokquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case nokquote.FieldID:
			values[i] = new(sql.NullInt64)
		case nokquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type NOKQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NOKQuote fields.
func (nq *NOKQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nokquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			nq.ID = int(value.Int64)
		case nokquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				nq.Price = value.Float64
			}
		case nokquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				nq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this NOKQuote.
// Note that you need to call NOKQuote.Unwrap() before calling this method if this NOKQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (nq *NOKQuote) Update() *NOKQuoteUpdateOne {
	return (&NOKQuoteClient{config: nq.config}).UpdateOne(nq)
}

// Unwrap unwraps the NOKQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (nq *NOKQuote) Unwrap() *NOKQuote {
	tx, ok := nq.config.driver.(*txDriver)
	if !ok {
		panic("ent: NOKQuote is not a transactional entity")
	}
	nq.config.driver = tx.drv
	return nq
}

// String implements the fmt.Stringer.
func (nq *NOKQuote) String() string {
	var builder strings.Builder
	builder.WriteString("NOKQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", nq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", nq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(nq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NOKQuotes is a parsable slice of NOKQuote.
type NOKQuotes []*NOKQuote

func (nq NOKQuotes) config(cfg config) {
	for _i := range nq {
		nq[_i].config = cfg
	}
}
