// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/nzdquote"
	"main/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NZDQuoteQuery is the builder for querying NZDQuote entities.
type NZDQuoteQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.NZDQuote
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NZDQuoteQuery builder.
func (nqq *NZDQuoteQuery) Where(ps ...predicate.NZDQuote) *NZDQuoteQuery {
	nqq.predicates = append(nqq.predicates, ps...)
	return nqq
}

// Limit adds a limit step to the query.
func (nqq *NZDQuoteQuery) Limit(limit int) *NZDQuoteQuery {
	nqq.limit = &limit
	return nqq
}

// Offset adds an offset step to the query.
func (nqq *NZDQuoteQuery) Offset(offset int) *NZDQuoteQuery {
	nqq.offset = &offset
	return nqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nqq *NZDQuoteQuery) Unique(unique bool) *NZDQuoteQuery {
	nqq.unique = &unique
	return nqq
}

// Order adds an order step to the query.
func (nqq *NZDQuoteQuery) Order(o ...OrderFunc) *NZDQuoteQuery {
	nqq.order = append(nqq.order, o...)
	return nqq
}

// First returns the first NZDQuote entity from the query.
// Returns a *NotFoundError when no NZDQuote was found.
func (nqq *NZDQuoteQuery) First(ctx context.Context) (*NZDQuote, error) {
	nodes, err := nqq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nzdquote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nqq *NZDQuoteQuery) FirstX(ctx context.Context) *NZDQuote {
	node, err := nqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NZDQuote ID from the query.
// Returns a *NotFoundError when no NZDQuote ID was found.
func (nqq *NZDQuoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nqq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nzdquote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nqq *NZDQuoteQuery) FirstIDX(ctx context.Context) int {
	id, err := nqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NZDQuote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NZDQuote entity is found.
// Returns a *NotFoundError when no NZDQuote entities are found.
func (nqq *NZDQuoteQuery) Only(ctx context.Context) (*NZDQuote, error) {
	nodes, err := nqq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nzdquote.Label}
	default:
		return nil, &NotSingularError{nzdquote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nqq *NZDQuoteQuery) OnlyX(ctx context.Context) *NZDQuote {
	node, err := nqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NZDQuote ID in the query.
// Returns a *NotSingularError when more than one NZDQuote ID is found.
// Returns a *NotFoundError when no entities are found.
func (nqq *NZDQuoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nqq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = &NotSingularError{nzdquote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nqq *NZDQuoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := nqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NZDQuotes.
func (nqq *NZDQuoteQuery) All(ctx context.Context) ([]*NZDQuote, error) {
	if err := nqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return nqq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (nqq *NZDQuoteQuery) AllX(ctx context.Context) []*NZDQuote {
	nodes, err := nqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NZDQuote IDs.
func (nqq *NZDQuoteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := nqq.Select(nzdquote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nqq *NZDQuoteQuery) IDsX(ctx context.Context) []int {
	ids, err := nqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nqq *NZDQuoteQuery) Count(ctx context.Context) (int, error) {
	if err := nqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return nqq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (nqq *NZDQuoteQuery) CountX(ctx context.Context) int {
	count, err := nqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nqq *NZDQuoteQuery) Exist(ctx context.Context) (bool, error) {
	if err := nqq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return nqq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (nqq *NZDQuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := nqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NZDQuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nqq *NZDQuoteQuery) Clone() *NZDQuoteQuery {
	if nqq == nil {
		return nil
	}
	return &NZDQuoteQuery{
		config:     nqq.config,
		limit:      nqq.limit,
		offset:     nqq.offset,
		order:      append([]OrderFunc{}, nqq.order...),
		predicates: append([]predicate.NZDQuote{}, nqq.predicates...),
		// clone intermediate query.
		sql:    nqq.sql.Clone(),
		path:   nqq.path,
		unique: nqq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NZDQuote.Query().
//		GroupBy(nzdquote.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (nqq *NZDQuoteQuery) GroupBy(field string, fields ...string) *NZDQuoteGroupBy {
	group := &NZDQuoteGroupBy{config: nqq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := nqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return nqq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.NZDQuote.Query().
//		Select(nzdquote.FieldPrice).
//		Scan(ctx, &v)
//
func (nqq *NZDQuoteQuery) Select(fields ...string) *NZDQuoteSelect {
	nqq.fields = append(nqq.fields, fields...)
	return &NZDQuoteSelect{NZDQuoteQuery: nqq}
}

func (nqq *NZDQuoteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range nqq.fields {
		if !nzdquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nqq.path != nil {
		prev, err := nqq.path(ctx)
		if err != nil {
			return err
		}
		nqq.sql = prev
	}
	return nil
}

func (nqq *NZDQuoteQuery) sqlAll(ctx context.Context) ([]*NZDQuote, error) {
	var (
		nodes = []*NZDQuote{}
		_spec = nqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &NZDQuote{config: nqq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, nqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nqq *NZDQuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nqq.querySpec()
	_spec.Node.Columns = nqq.fields
	if len(nqq.fields) > 0 {
		_spec.Unique = nqq.unique != nil && *nqq.unique
	}
	return sqlgraph.CountNodes(ctx, nqq.driver, _spec)
}

func (nqq *NZDQuoteQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := nqq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (nqq *NZDQuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   nzdquote.Table,
			Columns: nzdquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nzdquote.FieldID,
			},
		},
		From:   nqq.sql,
		Unique: true,
	}
	if unique := nqq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := nqq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nzdquote.FieldID)
		for i := range fields {
			if fields[i] != nzdquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nqq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nqq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nqq *NZDQuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nqq.driver.Dialect())
	t1 := builder.Table(nzdquote.Table)
	columns := nqq.fields
	if len(columns) == 0 {
		columns = nzdquote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nqq.sql != nil {
		selector = nqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nqq.unique != nil && *nqq.unique {
		selector.Distinct()
	}
	for _, p := range nqq.predicates {
		p(selector)
	}
	for _, p := range nqq.order {
		p(selector)
	}
	if offset := nqq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nqq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NZDQuoteGroupBy is the group-by builder for NZDQuote entities.
type NZDQuoteGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nqgb *NZDQuoteGroupBy) Aggregate(fns ...AggregateFunc) *NZDQuoteGroupBy {
	nqgb.fns = append(nqgb.fns, fns...)
	return nqgb
}

// Scan applies the group-by query and scans the result into the given value.
func (nqgb *NZDQuoteGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := nqgb.path(ctx)
	if err != nil {
		return err
	}
	nqgb.sql = query
	return nqgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := nqgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(nqgb.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := nqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) StringsX(ctx context.Context) []string {
	v, err := nqgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nqgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) StringX(ctx context.Context) string {
	v, err := nqgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(nqgb.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := nqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) IntsX(ctx context.Context) []int {
	v, err := nqgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nqgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) IntX(ctx context.Context) int {
	v, err := nqgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(nqgb.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := nqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := nqgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nqgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) Float64X(ctx context.Context) float64 {
	v, err := nqgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(nqgb.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := nqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := nqgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nqgb *NZDQuoteGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nqgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nqgb *NZDQuoteGroupBy) BoolX(ctx context.Context) bool {
	v, err := nqgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nqgb *NZDQuoteGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range nqgb.fields {
		if !nzdquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := nqgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nqgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nqgb *NZDQuoteGroupBy) sqlQuery() *sql.Selector {
	selector := nqgb.sql.Select()
	aggregation := make([]string, 0, len(nqgb.fns))
	for _, fn := range nqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(nqgb.fields)+len(nqgb.fns))
		for _, f := range nqgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(nqgb.fields...)...)
}

// NZDQuoteSelect is the builder for selecting fields of NZDQuote entities.
type NZDQuoteSelect struct {
	*NZDQuoteQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (nqs *NZDQuoteSelect) Scan(ctx context.Context, v interface{}) error {
	if err := nqs.prepareQuery(ctx); err != nil {
		return err
	}
	nqs.sql = nqs.NZDQuoteQuery.sqlQuery(ctx)
	return nqs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nqs *NZDQuoteSelect) ScanX(ctx context.Context, v interface{}) {
	if err := nqs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Strings(ctx context.Context) ([]string, error) {
	if len(nqs.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := nqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nqs *NZDQuoteSelect) StringsX(ctx context.Context) []string {
	v, err := nqs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nqs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nqs *NZDQuoteSelect) StringX(ctx context.Context) string {
	v, err := nqs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Ints(ctx context.Context) ([]int, error) {
	if len(nqs.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := nqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nqs *NZDQuoteSelect) IntsX(ctx context.Context) []int {
	v, err := nqs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nqs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nqs *NZDQuoteSelect) IntX(ctx context.Context) int {
	v, err := nqs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(nqs.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := nqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nqs *NZDQuoteSelect) Float64sX(ctx context.Context) []float64 {
	v, err := nqs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nqs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nqs *NZDQuoteSelect) Float64X(ctx context.Context) float64 {
	v, err := nqs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(nqs.fields) > 1 {
		return nil, errors.New("ent: NZDQuoteSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := nqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nqs *NZDQuoteSelect) BoolsX(ctx context.Context) []bool {
	v, err := nqs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (nqs *NZDQuoteSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nqs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nzdquote.Label}
	default:
		err = fmt.Errorf("ent: NZDQuoteSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nqs *NZDQuoteSelect) BoolX(ctx context.Context) bool {
	v, err := nqs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nqs *NZDQuoteSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := nqs.sql.Query()
	if err := nqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
