// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/pkrquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// PKRQuote is the model entity for the PKRQuote schema.
type PKRQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PKRQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case pkrquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case pkrquote.FieldID:
			values[i] = new(sql.NullInt64)
		case pkrquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PKRQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PKRQuote fields.
func (pq *PKRQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pkrquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pq.ID = int(value.Int64)
		case pkrquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				pq.Price = value.Float64
			}
		case pkrquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				pq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this PKRQuote.
// Note that you need to call PKRQuote.Unwrap() before calling this method if this PKRQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (pq *PKRQuote) Update() *PKRQuoteUpdateOne {
	return (&PKRQuoteClient{config: pq.config}).UpdateOne(pq)
}

// Unwrap unwraps the PKRQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pq *PKRQuote) Unwrap() *PKRQuote {
	tx, ok := pq.config.driver.(*txDriver)
	if !ok {
		panic("ent: PKRQuote is not a transactional entity")
	}
	pq.config.driver = tx.drv
	return pq
}

// String implements the fmt.Stringer.
func (pq *PKRQuote) String() string {
	var builder strings.Builder
	builder.WriteString("PKRQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", pq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", pq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(pq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PKRQuotes is a parsable slice of PKRQuote.
type PKRQuotes []*PKRQuote

func (pq PKRQuotes) config(cfg config) {
	for _i := range pq {
		pq[_i].config = cfg
	}
}
