// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/plnquote"
	"main/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PLNQuoteDelete is the builder for deleting a PLNQuote entity.
type PLNQuoteDelete struct {
	config
	hooks    []Hook
	mutation *PLNQuoteMutation
}

// Where appends a list predicates to the PLNQuoteDelete builder.
func (pqd *PLNQuoteDelete) Where(ps ...predicate.PLNQuote) *PLNQuoteDelete {
	pqd.mutation.Where(ps...)
	return pqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pqd *PLNQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pqd.hooks) == 0 {
		affected, err = pqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PLNQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pqd.mutation = mutation
			affected, err = pqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pqd.hooks) - 1; i >= 0; i-- {
			if pqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pqd *PLNQuoteDelete) ExecX(ctx context.Context) int {
	n, err := pqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pqd *PLNQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: plnquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: plnquote.FieldID,
			},
		},
	}
	if ps := pqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pqd.driver, _spec)
}

// PLNQuoteDeleteOne is the builder for deleting a single PLNQuote entity.
type PLNQuoteDeleteOne struct {
	pqd *PLNQuoteDelete
}

// Exec executes the deletion query.
func (pqdo *PLNQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := pqdo.pqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{plnquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pqdo *PLNQuoteDeleteOne) ExecX(ctx context.Context) {
	pqdo.pqd.ExecX(ctx)
}
