// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/rubquote"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RUBQuoteQuery is the builder for querying RUBQuote entities.
type RUBQuoteQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RUBQuote
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RUBQuoteQuery builder.
func (rqq *RUBQuoteQuery) Where(ps ...predicate.RUBQuote) *RUBQuoteQuery {
	rqq.predicates = append(rqq.predicates, ps...)
	return rqq
}

// Limit adds a limit step to the query.
func (rqq *RUBQuoteQuery) Limit(limit int) *RUBQuoteQuery {
	rqq.limit = &limit
	return rqq
}

// Offset adds an offset step to the query.
func (rqq *RUBQuoteQuery) Offset(offset int) *RUBQuoteQuery {
	rqq.offset = &offset
	return rqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rqq *RUBQuoteQuery) Unique(unique bool) *RUBQuoteQuery {
	rqq.unique = &unique
	return rqq
}

// Order adds an order step to the query.
func (rqq *RUBQuoteQuery) Order(o ...OrderFunc) *RUBQuoteQuery {
	rqq.order = append(rqq.order, o...)
	return rqq
}

// First returns the first RUBQuote entity from the query.
// Returns a *NotFoundError when no RUBQuote was found.
func (rqq *RUBQuoteQuery) First(ctx context.Context) (*RUBQuote, error) {
	nodes, err := rqq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rubquote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rqq *RUBQuoteQuery) FirstX(ctx context.Context) *RUBQuote {
	node, err := rqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RUBQuote ID from the query.
// Returns a *NotFoundError when no RUBQuote ID was found.
func (rqq *RUBQuoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rqq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rubquote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rqq *RUBQuoteQuery) FirstIDX(ctx context.Context) int {
	id, err := rqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RUBQuote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RUBQuote entity is found.
// Returns a *NotFoundError when no RUBQuote entities are found.
func (rqq *RUBQuoteQuery) Only(ctx context.Context) (*RUBQuote, error) {
	nodes, err := rqq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rubquote.Label}
	default:
		return nil, &NotSingularError{rubquote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rqq *RUBQuoteQuery) OnlyX(ctx context.Context) *RUBQuote {
	node, err := rqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RUBQuote ID in the query.
// Returns a *NotSingularError when more than one RUBQuote ID is found.
// Returns a *NotFoundError when no entities are found.
func (rqq *RUBQuoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rqq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = &NotSingularError{rubquote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rqq *RUBQuoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := rqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RUBQuotes.
func (rqq *RUBQuoteQuery) All(ctx context.Context) ([]*RUBQuote, error) {
	if err := rqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rqq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rqq *RUBQuoteQuery) AllX(ctx context.Context) []*RUBQuote {
	nodes, err := rqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RUBQuote IDs.
func (rqq *RUBQuoteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rqq.Select(rubquote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rqq *RUBQuoteQuery) IDsX(ctx context.Context) []int {
	ids, err := rqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rqq *RUBQuoteQuery) Count(ctx context.Context) (int, error) {
	if err := rqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rqq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rqq *RUBQuoteQuery) CountX(ctx context.Context) int {
	count, err := rqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rqq *RUBQuoteQuery) Exist(ctx context.Context) (bool, error) {
	if err := rqq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rqq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rqq *RUBQuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := rqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RUBQuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rqq *RUBQuoteQuery) Clone() *RUBQuoteQuery {
	if rqq == nil {
		return nil
	}
	return &RUBQuoteQuery{
		config:     rqq.config,
		limit:      rqq.limit,
		offset:     rqq.offset,
		order:      append([]OrderFunc{}, rqq.order...),
		predicates: append([]predicate.RUBQuote{}, rqq.predicates...),
		// clone intermediate query.
		sql:    rqq.sql.Clone(),
		path:   rqq.path,
		unique: rqq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RUBQuote.Query().
//		GroupBy(rubquote.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rqq *RUBQuoteQuery) GroupBy(field string, fields ...string) *RUBQuoteGroupBy {
	group := &RUBQuoteGroupBy{config: rqq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rqq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.RUBQuote.Query().
//		Select(rubquote.FieldPrice).
//		Scan(ctx, &v)
//
func (rqq *RUBQuoteQuery) Select(fields ...string) *RUBQuoteSelect {
	rqq.fields = append(rqq.fields, fields...)
	return &RUBQuoteSelect{RUBQuoteQuery: rqq}
}

func (rqq *RUBQuoteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rqq.fields {
		if !rubquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rqq.path != nil {
		prev, err := rqq.path(ctx)
		if err != nil {
			return err
		}
		rqq.sql = prev
	}
	return nil
}

func (rqq *RUBQuoteQuery) sqlAll(ctx context.Context) ([]*RUBQuote, error) {
	var (
		nodes = []*RUBQuote{}
		_spec = rqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &RUBQuote{config: rqq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, rqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rqq *RUBQuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rqq.querySpec()
	_spec.Node.Columns = rqq.fields
	if len(rqq.fields) > 0 {
		_spec.Unique = rqq.unique != nil && *rqq.unique
	}
	return sqlgraph.CountNodes(ctx, rqq.driver, _spec)
}

func (rqq *RUBQuoteQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rqq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rqq *RUBQuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rubquote.Table,
			Columns: rubquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rubquote.FieldID,
			},
		},
		From:   rqq.sql,
		Unique: true,
	}
	if unique := rqq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rqq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rubquote.FieldID)
		for i := range fields {
			if fields[i] != rubquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rqq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rqq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rqq *RUBQuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rqq.driver.Dialect())
	t1 := builder.Table(rubquote.Table)
	columns := rqq.fields
	if len(columns) == 0 {
		columns = rubquote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rqq.sql != nil {
		selector = rqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rqq.unique != nil && *rqq.unique {
		selector.Distinct()
	}
	for _, p := range rqq.predicates {
		p(selector)
	}
	for _, p := range rqq.order {
		p(selector)
	}
	if offset := rqq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rqq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RUBQuoteGroupBy is the group-by builder for RUBQuote entities.
type RUBQuoteGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rqgb *RUBQuoteGroupBy) Aggregate(fns ...AggregateFunc) *RUBQuoteGroupBy {
	rqgb.fns = append(rqgb.fns, fns...)
	return rqgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rqgb *RUBQuoteGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rqgb.path(ctx)
	if err != nil {
		return err
	}
	rqgb.sql = query
	return rqgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rqgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rqgb.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) StringsX(ctx context.Context) []string {
	v, err := rqgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rqgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) StringX(ctx context.Context) string {
	v, err := rqgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rqgb.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) IntsX(ctx context.Context) []int {
	v, err := rqgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rqgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) IntX(ctx context.Context) int {
	v, err := rqgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rqgb.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rqgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rqgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rqgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rqgb.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rqgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rqgb *RUBQuoteGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rqgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rqgb *RUBQuoteGroupBy) BoolX(ctx context.Context) bool {
	v, err := rqgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rqgb *RUBQuoteGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rqgb.fields {
		if !rubquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rqgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rqgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rqgb *RUBQuoteGroupBy) sqlQuery() *sql.Selector {
	selector := rqgb.sql.Select()
	aggregation := make([]string, 0, len(rqgb.fns))
	for _, fn := range rqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rqgb.fields)+len(rqgb.fns))
		for _, f := range rqgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rqgb.fields...)...)
}

// RUBQuoteSelect is the builder for selecting fields of RUBQuote entities.
type RUBQuoteSelect struct {
	*RUBQuoteQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rqs *RUBQuoteSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rqs.prepareQuery(ctx); err != nil {
		return err
	}
	rqs.sql = rqs.RUBQuoteQuery.sqlQuery(ctx)
	return rqs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rqs *RUBQuoteSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rqs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rqs.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rqs *RUBQuoteSelect) StringsX(ctx context.Context) []string {
	v, err := rqs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rqs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rqs *RUBQuoteSelect) StringX(ctx context.Context) string {
	v, err := rqs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rqs.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rqs *RUBQuoteSelect) IntsX(ctx context.Context) []int {
	v, err := rqs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rqs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rqs *RUBQuoteSelect) IntX(ctx context.Context) int {
	v, err := rqs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rqs.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rqs *RUBQuoteSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rqs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rqs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rqs *RUBQuoteSelect) Float64X(ctx context.Context) float64 {
	v, err := rqs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rqs.fields) > 1 {
		return nil, errors.New("ent: RUBQuoteSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rqs *RUBQuoteSelect) BoolsX(ctx context.Context) []bool {
	v, err := rqs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (rqs *RUBQuoteSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rqs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubquote.Label}
	default:
		err = fmt.Errorf("ent: RUBQuoteSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rqs *RUBQuoteSelect) BoolX(ctx context.Context) bool {
	v, err := rqs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rqs *RUBQuoteSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rqs.sql.Query()
	if err := rqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
