// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/rubquote"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RUBQuoteUpdate is the builder for updating RUBQuote entities.
type RUBQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *RUBQuoteMutation
}

// Where appends a list predicates to the RUBQuoteUpdate builder.
func (rqu *RUBQuoteUpdate) Where(ps ...predicate.RUBQuote) *RUBQuoteUpdate {
	rqu.mutation.Where(ps...)
	return rqu
}

// SetPrice sets the "price" field.
func (rqu *RUBQuoteUpdate) SetPrice(f float64) *RUBQuoteUpdate {
	rqu.mutation.ResetPrice()
	rqu.mutation.SetPrice(f)
	return rqu
}

// AddPrice adds f to the "price" field.
func (rqu *RUBQuoteUpdate) AddPrice(f float64) *RUBQuoteUpdate {
	rqu.mutation.AddPrice(f)
	return rqu
}

// SetTimestamp sets the "Timestamp" field.
func (rqu *RUBQuoteUpdate) SetTimestamp(t time.Time) *RUBQuoteUpdate {
	rqu.mutation.SetTimestamp(t)
	return rqu
}

// Mutation returns the RUBQuoteMutation object of the builder.
func (rqu *RUBQuoteUpdate) Mutation() *RUBQuoteMutation {
	return rqu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rqu *RUBQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rqu.hooks) == 0 {
		affected, err = rqu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RUBQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rqu.mutation = mutation
			affected, err = rqu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rqu.hooks) - 1; i >= 0; i-- {
			if rqu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rqu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rqu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (rqu *RUBQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := rqu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rqu *RUBQuoteUpdate) Exec(ctx context.Context) error {
	_, err := rqu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rqu *RUBQuoteUpdate) ExecX(ctx context.Context) {
	if err := rqu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rqu *RUBQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rubquote.Table,
			Columns: rubquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rubquote.FieldID,
			},
		},
	}
	if ps := rqu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rqu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: rubquote.FieldPrice,
		})
	}
	if value, ok := rqu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: rubquote.FieldPrice,
		})
	}
	if value, ok := rqu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: rubquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rqu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rubquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// RUBQuoteUpdateOne is the builder for updating a single RUBQuote entity.
type RUBQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RUBQuoteMutation
}

// SetPrice sets the "price" field.
func (rquo *RUBQuoteUpdateOne) SetPrice(f float64) *RUBQuoteUpdateOne {
	rquo.mutation.ResetPrice()
	rquo.mutation.SetPrice(f)
	return rquo
}

// AddPrice adds f to the "price" field.
func (rquo *RUBQuoteUpdateOne) AddPrice(f float64) *RUBQuoteUpdateOne {
	rquo.mutation.AddPrice(f)
	return rquo
}

// SetTimestamp sets the "Timestamp" field.
func (rquo *RUBQuoteUpdateOne) SetTimestamp(t time.Time) *RUBQuoteUpdateOne {
	rquo.mutation.SetTimestamp(t)
	return rquo
}

// Mutation returns the RUBQuoteMutation object of the builder.
func (rquo *RUBQuoteUpdateOne) Mutation() *RUBQuoteMutation {
	return rquo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rquo *RUBQuoteUpdateOne) Select(field string, fields ...string) *RUBQuoteUpdateOne {
	rquo.fields = append([]string{field}, fields...)
	return rquo
}

// Save executes the query and returns the updated RUBQuote entity.
func (rquo *RUBQuoteUpdateOne) Save(ctx context.Context) (*RUBQuote, error) {
	var (
		err  error
		node *RUBQuote
	)
	if len(rquo.hooks) == 0 {
		node, err = rquo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RUBQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rquo.mutation = mutation
			node, err = rquo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rquo.hooks) - 1; i >= 0; i-- {
			if rquo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rquo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rquo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (rquo *RUBQuoteUpdateOne) SaveX(ctx context.Context) *RUBQuote {
	node, err := rquo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rquo *RUBQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := rquo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rquo *RUBQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := rquo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rquo *RUBQuoteUpdateOne) sqlSave(ctx context.Context) (_node *RUBQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rubquote.Table,
			Columns: rubquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rubquote.FieldID,
			},
		},
	}
	id, ok := rquo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RUBQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rquo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rubquote.FieldID)
		for _, f := range fields {
			if !rubquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rubquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rquo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rquo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: rubquote.FieldPrice,
		})
	}
	if value, ok := rquo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: rubquote.FieldPrice,
		})
	}
	if value, ok := rquo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: rubquote.FieldTimestamp,
		})
	}
	_node = &RUBQuote{config: rquo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rquo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rubquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
