// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/sarquote"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SARQuoteUpdate is the builder for updating SARQuote entities.
type SARQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *SARQuoteMutation
}

// Where appends a list predicates to the SARQuoteUpdate builder.
func (squ *SARQuoteUpdate) Where(ps ...predicate.SARQuote) *SARQuoteUpdate {
	squ.mutation.Where(ps...)
	return squ
}

// SetPrice sets the "price" field.
func (squ *SARQuoteUpdate) SetPrice(f float64) *SARQuoteUpdate {
	squ.mutation.ResetPrice()
	squ.mutation.SetPrice(f)
	return squ
}

// AddPrice adds f to the "price" field.
func (squ *SARQuoteUpdate) AddPrice(f float64) *SARQuoteUpdate {
	squ.mutation.AddPrice(f)
	return squ
}

// SetTimestamp sets the "Timestamp" field.
func (squ *SARQuoteUpdate) SetTimestamp(t time.Time) *SARQuoteUpdate {
	squ.mutation.SetTimestamp(t)
	return squ
}

// Mutation returns the SARQuoteMutation object of the builder.
func (squ *SARQuoteUpdate) Mutation() *SARQuoteMutation {
	return squ.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (squ *SARQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(squ.hooks) == 0 {
		affected, err = squ.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SARQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			squ.mutation = mutation
			affected, err = squ.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(squ.hooks) - 1; i >= 0; i-- {
			if squ.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = squ.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, squ.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (squ *SARQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := squ.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (squ *SARQuoteUpdate) Exec(ctx context.Context) error {
	_, err := squ.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (squ *SARQuoteUpdate) ExecX(ctx context.Context) {
	if err := squ.Exec(ctx); err != nil {
		panic(err)
	}
}

func (squ *SARQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sarquote.Table,
			Columns: sarquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sarquote.FieldID,
			},
		},
	}
	if ps := squ.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := squ.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sarquote.FieldPrice,
		})
	}
	if value, ok := squ.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sarquote.FieldPrice,
		})
	}
	if value, ok := squ.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sarquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, squ.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sarquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SARQuoteUpdateOne is the builder for updating a single SARQuote entity.
type SARQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SARQuoteMutation
}

// SetPrice sets the "price" field.
func (squo *SARQuoteUpdateOne) SetPrice(f float64) *SARQuoteUpdateOne {
	squo.mutation.ResetPrice()
	squo.mutation.SetPrice(f)
	return squo
}

// AddPrice adds f to the "price" field.
func (squo *SARQuoteUpdateOne) AddPrice(f float64) *SARQuoteUpdateOne {
	squo.mutation.AddPrice(f)
	return squo
}

// SetTimestamp sets the "Timestamp" field.
func (squo *SARQuoteUpdateOne) SetTimestamp(t time.Time) *SARQuoteUpdateOne {
	squo.mutation.SetTimestamp(t)
	return squo
}

// Mutation returns the SARQuoteMutation object of the builder.
func (squo *SARQuoteUpdateOne) Mutation() *SARQuoteMutation {
	return squo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (squo *SARQuoteUpdateOne) Select(field string, fields ...string) *SARQuoteUpdateOne {
	squo.fields = append([]string{field}, fields...)
	return squo
}

// Save executes the query and returns the updated SARQuote entity.
func (squo *SARQuoteUpdateOne) Save(ctx context.Context) (*SARQuote, error) {
	var (
		err  error
		node *SARQuote
	)
	if len(squo.hooks) == 0 {
		node, err = squo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SARQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			squo.mutation = mutation
			node, err = squo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(squo.hooks) - 1; i >= 0; i-- {
			if squo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = squo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, squo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (squo *SARQuoteUpdateOne) SaveX(ctx context.Context) *SARQuote {
	node, err := squo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (squo *SARQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := squo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (squo *SARQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := squo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (squo *SARQuoteUpdateOne) sqlSave(ctx context.Context) (_node *SARQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sarquote.Table,
			Columns: sarquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sarquote.FieldID,
			},
		},
	}
	id, ok := squo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SARQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := squo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sarquote.FieldID)
		for _, f := range fields {
			if !sarquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sarquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := squo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := squo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sarquote.FieldPrice,
		})
	}
	if value, ok := squo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sarquote.FieldPrice,
		})
	}
	if value, ok := squo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sarquote.FieldTimestamp,
		})
	}
	_node = &SARQuote{config: squo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, squo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sarquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
