// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/predicate"
	"main/ent/tryquote"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TRYQuoteDelete is the builder for deleting a TRYQuote entity.
type TRYQuoteDelete struct {
	config
	hooks    []Hook
	mutation *TRYQuoteMutation
}

// Where appends a list predicates to the TRYQuoteDelete builder.
func (tqd *TRYQuoteDelete) Where(ps ...predicate.TRYQuote) *TRYQuoteDelete {
	tqd.mutation.Where(ps...)
	return tqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tqd *TRYQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tqd.hooks) == 0 {
		affected, err = tqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TRYQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tqd.mutation = mutation
			affected, err = tqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tqd.hooks) - 1; i >= 0; i-- {
			if tqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tqd *TRYQuoteDelete) ExecX(ctx context.Context) int {
	n, err := tqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tqd *TRYQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tryquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tryquote.FieldID,
			},
		},
	}
	if ps := tqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tqd.driver, _spec)
}

// TRYQuoteDeleteOne is the builder for deleting a single TRYQuote entity.
type TRYQuoteDeleteOne struct {
	tqd *TRYQuoteDelete
}

// Exec executes the deletion query.
func (tqdo *TRYQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := tqdo.tqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tryquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tqdo *TRYQuoteDeleteOne) ExecX(ctx context.Context) {
	tqdo.tqd.ExecX(ctx)
}
