// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/twdquote"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TWDQuoteQuery is the builder for querying TWDQuote entities.
type TWDQuoteQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TWDQuote
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TWDQuoteQuery builder.
func (tqq *TWDQuoteQuery) Where(ps ...predicate.TWDQuote) *TWDQuoteQuery {
	tqq.predicates = append(tqq.predicates, ps...)
	return tqq
}

// Limit adds a limit step to the query.
func (tqq *TWDQuoteQuery) Limit(limit int) *TWDQuoteQuery {
	tqq.limit = &limit
	return tqq
}

// Offset adds an offset step to the query.
func (tqq *TWDQuoteQuery) Offset(offset int) *TWDQuoteQuery {
	tqq.offset = &offset
	return tqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tqq *TWDQuoteQuery) Unique(unique bool) *TWDQuoteQuery {
	tqq.unique = &unique
	return tqq
}

// Order adds an order step to the query.
func (tqq *TWDQuoteQuery) Order(o ...OrderFunc) *TWDQuoteQuery {
	tqq.order = append(tqq.order, o...)
	return tqq
}

// First returns the first TWDQuote entity from the query.
// Returns a *NotFoundError when no TWDQuote was found.
func (tqq *TWDQuoteQuery) First(ctx context.Context) (*TWDQuote, error) {
	nodes, err := tqq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{twdquote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tqq *TWDQuoteQuery) FirstX(ctx context.Context) *TWDQuote {
	node, err := tqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TWDQuote ID from the query.
// Returns a *NotFoundError when no TWDQuote ID was found.
func (tqq *TWDQuoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tqq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{twdquote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tqq *TWDQuoteQuery) FirstIDX(ctx context.Context) int {
	id, err := tqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TWDQuote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TWDQuote entity is found.
// Returns a *NotFoundError when no TWDQuote entities are found.
func (tqq *TWDQuoteQuery) Only(ctx context.Context) (*TWDQuote, error) {
	nodes, err := tqq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{twdquote.Label}
	default:
		return nil, &NotSingularError{twdquote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tqq *TWDQuoteQuery) OnlyX(ctx context.Context) *TWDQuote {
	node, err := tqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TWDQuote ID in the query.
// Returns a *NotSingularError when more than one TWDQuote ID is found.
// Returns a *NotFoundError when no entities are found.
func (tqq *TWDQuoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tqq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = &NotSingularError{twdquote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tqq *TWDQuoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := tqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TWDQuotes.
func (tqq *TWDQuoteQuery) All(ctx context.Context) ([]*TWDQuote, error) {
	if err := tqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tqq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tqq *TWDQuoteQuery) AllX(ctx context.Context) []*TWDQuote {
	nodes, err := tqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TWDQuote IDs.
func (tqq *TWDQuoteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tqq.Select(twdquote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tqq *TWDQuoteQuery) IDsX(ctx context.Context) []int {
	ids, err := tqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tqq *TWDQuoteQuery) Count(ctx context.Context) (int, error) {
	if err := tqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tqq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tqq *TWDQuoteQuery) CountX(ctx context.Context) int {
	count, err := tqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tqq *TWDQuoteQuery) Exist(ctx context.Context) (bool, error) {
	if err := tqq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tqq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tqq *TWDQuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := tqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TWDQuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tqq *TWDQuoteQuery) Clone() *TWDQuoteQuery {
	if tqq == nil {
		return nil
	}
	return &TWDQuoteQuery{
		config:     tqq.config,
		limit:      tqq.limit,
		offset:     tqq.offset,
		order:      append([]OrderFunc{}, tqq.order...),
		predicates: append([]predicate.TWDQuote{}, tqq.predicates...),
		// clone intermediate query.
		sql:    tqq.sql.Clone(),
		path:   tqq.path,
		unique: tqq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TWDQuote.Query().
//		GroupBy(twdquote.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tqq *TWDQuoteQuery) GroupBy(field string, fields ...string) *TWDQuoteGroupBy {
	group := &TWDQuoteGroupBy{config: tqq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tqq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.TWDQuote.Query().
//		Select(twdquote.FieldPrice).
//		Scan(ctx, &v)
//
func (tqq *TWDQuoteQuery) Select(fields ...string) *TWDQuoteSelect {
	tqq.fields = append(tqq.fields, fields...)
	return &TWDQuoteSelect{TWDQuoteQuery: tqq}
}

func (tqq *TWDQuoteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tqq.fields {
		if !twdquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tqq.path != nil {
		prev, err := tqq.path(ctx)
		if err != nil {
			return err
		}
		tqq.sql = prev
	}
	return nil
}

func (tqq *TWDQuoteQuery) sqlAll(ctx context.Context) ([]*TWDQuote, error) {
	var (
		nodes = []*TWDQuote{}
		_spec = tqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TWDQuote{config: tqq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tqq *TWDQuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tqq.querySpec()
	_spec.Node.Columns = tqq.fields
	if len(tqq.fields) > 0 {
		_spec.Unique = tqq.unique != nil && *tqq.unique
	}
	return sqlgraph.CountNodes(ctx, tqq.driver, _spec)
}

func (tqq *TWDQuoteQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tqq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tqq *TWDQuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   twdquote.Table,
			Columns: twdquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: twdquote.FieldID,
			},
		},
		From:   tqq.sql,
		Unique: true,
	}
	if unique := tqq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tqq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, twdquote.FieldID)
		for i := range fields {
			if fields[i] != twdquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tqq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tqq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tqq *TWDQuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tqq.driver.Dialect())
	t1 := builder.Table(twdquote.Table)
	columns := tqq.fields
	if len(columns) == 0 {
		columns = twdquote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tqq.sql != nil {
		selector = tqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tqq.unique != nil && *tqq.unique {
		selector.Distinct()
	}
	for _, p := range tqq.predicates {
		p(selector)
	}
	for _, p := range tqq.order {
		p(selector)
	}
	if offset := tqq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tqq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TWDQuoteGroupBy is the group-by builder for TWDQuote entities.
type TWDQuoteGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tqgb *TWDQuoteGroupBy) Aggregate(fns ...AggregateFunc) *TWDQuoteGroupBy {
	tqgb.fns = append(tqgb.fns, fns...)
	return tqgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tqgb *TWDQuoteGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tqgb.path(ctx)
	if err != nil {
		return err
	}
	tqgb.sql = query
	return tqgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tqgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tqgb.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) StringsX(ctx context.Context) []string {
	v, err := tqgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tqgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) StringX(ctx context.Context) string {
	v, err := tqgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tqgb.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) IntsX(ctx context.Context) []int {
	v, err := tqgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tqgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) IntX(ctx context.Context) int {
	v, err := tqgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tqgb.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tqgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tqgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tqgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tqgb.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tqgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tqgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tqgb *TWDQuoteGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tqgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tqgb *TWDQuoteGroupBy) BoolX(ctx context.Context) bool {
	v, err := tqgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tqgb *TWDQuoteGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tqgb.fields {
		if !twdquote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tqgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tqgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tqgb *TWDQuoteGroupBy) sqlQuery() *sql.Selector {
	selector := tqgb.sql.Select()
	aggregation := make([]string, 0, len(tqgb.fns))
	for _, fn := range tqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tqgb.fields)+len(tqgb.fns))
		for _, f := range tqgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tqgb.fields...)...)
}

// TWDQuoteSelect is the builder for selecting fields of TWDQuote entities.
type TWDQuoteSelect struct {
	*TWDQuoteQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tqs *TWDQuoteSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tqs.prepareQuery(ctx); err != nil {
		return err
	}
	tqs.sql = tqs.TWDQuoteQuery.sqlQuery(ctx)
	return tqs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tqs *TWDQuoteSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tqs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tqs.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tqs *TWDQuoteSelect) StringsX(ctx context.Context) []string {
	v, err := tqs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tqs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tqs *TWDQuoteSelect) StringX(ctx context.Context) string {
	v, err := tqs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tqs.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tqs *TWDQuoteSelect) IntsX(ctx context.Context) []int {
	v, err := tqs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tqs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tqs *TWDQuoteSelect) IntX(ctx context.Context) int {
	v, err := tqs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tqs.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tqs *TWDQuoteSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tqs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tqs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tqs *TWDQuoteSelect) Float64X(ctx context.Context) float64 {
	v, err := tqs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tqs.fields) > 1 {
		return nil, errors.New("ent: TWDQuoteSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tqs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tqs *TWDQuoteSelect) BoolsX(ctx context.Context) []bool {
	v, err := tqs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tqs *TWDQuoteSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tqs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twdquote.Label}
	default:
		err = fmt.Errorf("ent: TWDQuoteSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tqs *TWDQuoteSelect) BoolX(ctx context.Context) bool {
	v, err := tqs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tqs *TWDQuoteSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tqs.sql.Query()
	if err := tqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
