// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/predicate"
	"main/ent/uahquote"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UAHQuoteDelete is the builder for deleting a UAHQuote entity.
type UAHQuoteDelete struct {
	config
	hooks    []Hook
	mutation *UAHQuoteMutation
}

// Where appends a list predicates to the UAHQuoteDelete builder.
func (uqd *UAHQuoteDelete) Where(ps ...predicate.UAHQuote) *UAHQuoteDelete {
	uqd.mutation.Where(ps...)
	return uqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uqd *UAHQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uqd.hooks) == 0 {
		affected, err = uqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UAHQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uqd.mutation = mutation
			affected, err = uqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uqd.hooks) - 1; i >= 0; i-- {
			if uqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uqd *UAHQuoteDelete) ExecX(ctx context.Context) int {
	n, err := uqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uqd *UAHQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: uahquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: uahquote.FieldID,
			},
		},
	}
	if ps := uqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uqd.driver, _spec)
}

// UAHQuoteDeleteOne is the builder for deleting a single UAHQuote entity.
type UAHQuoteDeleteOne struct {
	uqd *UAHQuoteDelete
}

// Exec executes the deletion query.
func (uqdo *UAHQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := uqdo.uqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uahquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uqdo *UAHQuoteDeleteOne) ExecX(ctx context.Context) {
	uqdo.uqd.ExecX(ctx)
}
