// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/usdquote"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// USDQuoteCreate is the builder for creating a USDQuote entity.
type USDQuoteCreate struct {
	config
	mutation *USDQuoteMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (uqc *USDQuoteCreate) SetPrice(f float64) *USDQuoteCreate {
	uqc.mutation.SetPrice(f)
	return uqc
}

// SetTimestamp sets the "Timestamp" field.
func (uqc *USDQuoteCreate) SetTimestamp(t time.Time) *USDQuoteCreate {
	uqc.mutation.SetTimestamp(t)
	return uqc
}

// SetID sets the "id" field.
func (uqc *USDQuoteCreate) SetID(i int) *USDQuoteCreate {
	uqc.mutation.SetID(i)
	return uqc
}

// Mutation returns the USDQuoteMutation object of the builder.
func (uqc *USDQuoteCreate) Mutation() *USDQuoteMutation {
	return uqc.mutation
}

// Save creates the USDQuote in the database.
func (uqc *USDQuoteCreate) Save(ctx context.Context) (*USDQuote, error) {
	var (
		err  error
		node *USDQuote
	)
	if len(uqc.hooks) == 0 {
		if err = uqc.check(); err != nil {
			return nil, err
		}
		node, err = uqc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*USDQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uqc.check(); err != nil {
				return nil, err
			}
			uqc.mutation = mutation
			if node, err = uqc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uqc.hooks) - 1; i >= 0; i-- {
			if uqc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uqc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uqc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uqc *USDQuoteCreate) SaveX(ctx context.Context) *USDQuote {
	v, err := uqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uqc *USDQuoteCreate) Exec(ctx context.Context) error {
	_, err := uqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uqc *USDQuoteCreate) ExecX(ctx context.Context) {
	if err := uqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uqc *USDQuoteCreate) check() error {
	if _, ok := uqc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "USDQuote.price"`)}
	}
	if _, ok := uqc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "Timestamp", err: errors.New(`ent: missing required field "USDQuote.Timestamp"`)}
	}
	return nil
}

func (uqc *USDQuoteCreate) sqlSave(ctx context.Context) (*USDQuote, error) {
	_node, _spec := uqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (uqc *USDQuoteCreate) createSpec() (*USDQuote, *sqlgraph.CreateSpec) {
	var (
		_node = &USDQuote{config: uqc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: usdquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usdquote.FieldID,
			},
		}
	)
	if id, ok := uqc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uqc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: usdquote.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := uqc.mutation.Timestamp(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usdquote.FieldTimestamp,
		})
		_node.Timestamp = value
	}
	return _node, _spec
}

// USDQuoteCreateBulk is the builder for creating many USDQuote entities in bulk.
type USDQuoteCreateBulk struct {
	config
	builders []*USDQuoteCreate
}

// Save creates the USDQuote entities in the database.
func (uqcb *USDQuoteCreateBulk) Save(ctx context.Context) ([]*USDQuote, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uqcb.builders))
	nodes := make([]*USDQuote, len(uqcb.builders))
	mutators := make([]Mutator, len(uqcb.builders))
	for i := range uqcb.builders {
		func(i int, root context.Context) {
			builder := uqcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*USDQuoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uqcb *USDQuoteCreateBulk) SaveX(ctx context.Context) []*USDQuote {
	v, err := uqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uqcb *USDQuoteCreateBulk) Exec(ctx context.Context) error {
	_, err := uqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uqcb *USDQuoteCreateBulk) ExecX(ctx context.Context) {
	if err := uqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
