// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/zarquote"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ZARQuoteUpdate is the builder for updating ZARQuote entities.
type ZARQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *ZARQuoteMutation
}

// Where appends a list predicates to the ZARQuoteUpdate builder.
func (zqu *ZARQuoteUpdate) Where(ps ...predicate.ZARQuote) *ZARQuoteUpdate {
	zqu.mutation.Where(ps...)
	return zqu
}

// SetPrice sets the "price" field.
func (zqu *ZARQuoteUpdate) SetPrice(f float64) *ZARQuoteUpdate {
	zqu.mutation.ResetPrice()
	zqu.mutation.SetPrice(f)
	return zqu
}

// AddPrice adds f to the "price" field.
func (zqu *ZARQuoteUpdate) AddPrice(f float64) *ZARQuoteUpdate {
	zqu.mutation.AddPrice(f)
	return zqu
}

// SetTimestamp sets the "Timestamp" field.
func (zqu *ZARQuoteUpdate) SetTimestamp(t time.Time) *ZARQuoteUpdate {
	zqu.mutation.SetTimestamp(t)
	return zqu
}

// Mutation returns the ZARQuoteMutation object of the builder.
func (zqu *ZARQuoteUpdate) Mutation() *ZARQuoteMutation {
	return zqu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (zqu *ZARQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(zqu.hooks) == 0 {
		affected, err = zqu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ZARQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			zqu.mutation = mutation
			affected, err = zqu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(zqu.hooks) - 1; i >= 0; i-- {
			if zqu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = zqu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, zqu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (zqu *ZARQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := zqu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (zqu *ZARQuoteUpdate) Exec(ctx context.Context) error {
	_, err := zqu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (zqu *ZARQuoteUpdate) ExecX(ctx context.Context) {
	if err := zqu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (zqu *ZARQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   zarquote.Table,
			Columns: zarquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: zarquote.FieldID,
			},
		},
	}
	if ps := zqu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := zqu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: zarquote.FieldPrice,
		})
	}
	if value, ok := zqu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: zarquote.FieldPrice,
		})
	}
	if value, ok := zqu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: zarquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, zqu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zarquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ZARQuoteUpdateOne is the builder for updating a single ZARQuote entity.
type ZARQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ZARQuoteMutation
}

// SetPrice sets the "price" field.
func (zquo *ZARQuoteUpdateOne) SetPrice(f float64) *ZARQuoteUpdateOne {
	zquo.mutation.ResetPrice()
	zquo.mutation.SetPrice(f)
	return zquo
}

// AddPrice adds f to the "price" field.
func (zquo *ZARQuoteUpdateOne) AddPrice(f float64) *ZARQuoteUpdateOne {
	zquo.mutation.AddPrice(f)
	return zquo
}

// SetTimestamp sets the "Timestamp" field.
func (zquo *ZARQuoteUpdateOne) SetTimestamp(t time.Time) *ZARQuoteUpdateOne {
	zquo.mutation.SetTimestamp(t)
	return zquo
}

// Mutation returns the ZARQuoteMutation object of the builder.
func (zquo *ZARQuoteUpdateOne) Mutation() *ZARQuoteMutation {
	return zquo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (zquo *ZARQuoteUpdateOne) Select(field string, fields ...string) *ZARQuoteUpdateOne {
	zquo.fields = append([]string{field}, fields...)
	return zquo
}

// Save executes the query and returns the updated ZARQuote entity.
func (zquo *ZARQuoteUpdateOne) Save(ctx context.Context) (*ZARQuote, error) {
	var (
		err  error
		node *ZARQuote
	)
	if len(zquo.hooks) == 0 {
		node, err = zquo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ZARQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			zquo.mutation = mutation
			node, err = zquo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(zquo.hooks) - 1; i >= 0; i-- {
			if zquo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = zquo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, zquo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (zquo *ZARQuoteUpdateOne) SaveX(ctx context.Context) *ZARQuote {
	node, err := zquo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (zquo *ZARQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := zquo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (zquo *ZARQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := zquo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (zquo *ZARQuoteUpdateOne) sqlSave(ctx context.Context) (_node *ZARQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   zarquote.Table,
			Columns: zarquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: zarquote.FieldID,
			},
		},
	}
	id, ok := zquo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ZARQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := zquo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, zarquote.FieldID)
		for _, f := range fields {
			if !zarquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != zarquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := zquo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := zquo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: zarquote.FieldPrice,
		})
	}
	if value, ok := zquo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: zarquote.FieldPrice,
		})
	}
	if value, ok := zquo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: zarquote.FieldTimestamp,
		})
	}
	_node = &ZARQuote{config: zquo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, zquo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zarquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
