// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/zarquote"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ZARQuote is the model entity for the ZARQuote schema.
type ZARQuote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ZARQuote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case zarquote.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case zarquote.FieldID:
			values[i] = new(sql.NullInt64)
		case zarquote.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ZARQuote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ZARQuote fields.
func (zq *ZARQuote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case zarquote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			zq.ID = int(value.Int64)
		case zarquote.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				zq.Price = value.Float64
			}
		case zarquote.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				zq.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this ZARQuote.
// Note that you need to call ZARQuote.Unwrap() before calling this method if this ZARQuote
// was returned from a transaction, and the transaction was committed or rolled back.
func (zq *ZARQuote) Update() *ZARQuoteUpdateOne {
	return (&ZARQuoteClient{config: zq.config}).UpdateOne(zq)
}

// Unwrap unwraps the ZARQuote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (zq *ZARQuote) Unwrap() *ZARQuote {
	tx, ok := zq.config.driver.(*txDriver)
	if !ok {
		panic("ent: ZARQuote is not a transactional entity")
	}
	zq.config.driver = tx.drv
	return zq
}

// String implements the fmt.Stringer.
func (zq *ZARQuote) String() string {
	var builder strings.Builder
	builder.WriteString("ZARQuote(")
	builder.WriteString(fmt.Sprintf("id=%v", zq.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", zq.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(zq.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ZARQuotes is a parsable slice of ZARQuote.
type ZARQuotes []*ZARQuote

func (zq ZARQuotes) config(cfg config) {
	for _i := range zq {
		zq[_i].config = cfg
	}
}
